Repository SynoCommunity/spksrc, pull requests merged in 2018-09, with the labels that each got.

#3424 ps3netsrv: location with whitespaces fix #3399
  cross/ps3netsrv/Makefile
  cross/ps3netsrv/digests
  spk/ps3netsrv/Makefile
  spk/ps3netsrv/src/ps3netsrv-starter.sh
  spk/ps3netsrv/src/ps3netsrv.conf
  spk/ps3netsrv/src/service-setup.sh
  spk/ps3netsrv/src/wizard/install_uifile_rus
Labels: status/to-publish

#3431 Gateone - Update to git-6ae1d01 and generic DSM5+6 service approach
  cross/dtach/Makefile
  cross/dtach/digests
  cross/gateone/Makefile
  spk/gateone/Makefile
  spk/gateone/src/90custom.conf
  spk/gateone/src/app/config
  spk/gateone/src/conf/privilege
  spk/gateone/src/dsm-control.sh
  spk/gateone/src/gateone.sc
  spk/gateone/src/installer.sh
  spk/gateone/src/requirements.txt
  spk/gateone/src/service-setup.sh
Labels: status/ready-to-merge, status/to-publish

#3450 he853: update with generic installer for DSM 6
  spk/he853/Makefile
  spk/he853/src/dsm-control.sh
  spk/he853/src/installer.sh
  spk/he853/src/service-setup.sh
Labels: status/ready-to-merge

#3445 Update SABnzbd to 2.3.5
  cross/sabnzbd/Makefile
  cross/sabnzbd/digests
  spk/sabnzbd/Makefile
Labels: status/to-publish

#3455 Update zsh packages to 5.6.1
  cross/zsh/Makefile
  cross/zsh/digests
  spk/zsh-static/Makefile
  spk/zsh/Makefile
Labels: status/to-publish
