Repository SynoCommunity/spksrc, pull requests merged in 2018-02, with the labels that each got.

#3149 Cross cleanup
  cross/apr-util/Makefile
  cross/apr-util/PLIST
  cross/apr-util/digests
  cross/apr/Makefile
  cross/apr/PLIST
  cross/apr/digests
  cross/apr/patches/gen_test_char.patch
  cross/dbus/Makefile
  cross/dbus/PLIST
  cross/dbus/digests
  cross/iksemel/Makefile
  cross/iksemel/PLIST
  cross/iksemel/digests
  cross/libcap2/Makefile
  cross/libcap2/PLIST
  cross/libcap2/digests
  cross/libcap2/patches/make.patch
  cross/libical/Makefile
  cross/libical/PLIST
  cross/libical/digests
  cross/neon/Makefile
  cross/neon/PLIST
  cross/neon/digests
  cross/serf/Makefile
  cross/serf/PLIST
  cross/serf/digests
  cross/tinyproxy/Makefile
  cross/tinyproxy/PLIST
  cross/tinyproxy/patches/010-no-docs-and-tests.patch
  cross/xzdec-static/Makefile
  cross/xzdec-static/PLIST
Labels: status/ready-to-merge

#3143 Midnight Commander 4.8.20 and use Generic Service
  cross/glib/Makefile
  cross/glib/PLIST
  cross/glib/digests
  cross/libffi/Makefile
  cross/mc/Makefile
  cross/mc/digests
  cross/ncurses/Makefile
  cross/ncurses/PLIST
  cross/ncurses/digests
  cross/ncursesw/Makefile
  cross/ncursesw/PLIST
  cross/ncursesw/digests
  cross/pcre/Makefile
  cross/pcre/PLIST
  cross/pcre/digests
  native/glib/Makefile
  spk/mc/Makefile
  spk/mc/src/dsm-control.sh
  spk/mc/src/installer.sh
  spk/mc/src/service-setup.sh
Labels: status/work-in-progress

#3155 Remove references to deprecated arch 88f5281
  cross/alsa-lib/Makefile
  cross/alsa-lib/patches/001-no-tls-pfx.patch
  cross/bison/Makefile
  cross/erlang/Makefile
  cross/gmp/Makefile
  cross/gnutls/Makefile
  cross/libxml2/Makefile
  cross/lxml/Makefile
  cross/nettle/Makefile
  cross/rtorrent/Makefile
  cross/syncthing-inotify/Makefile
  cross/syncthing/Makefile
  mk/spksrc.common.mk
  spk/ffsync/Makefile
  spk/lirc/Makefile
Labels: arch, status/needs-review

#3156 Python correct Busybox and re-introduce pyasn1
  cross/pyasn1/Makefile
  cross/pyasn1/PLIST
  cross/pyasn1/digests
  spk/python/src/requirements.txt
  spk/python/src/service-setup.sh
Labels: status/to-publish

#3161 Add set_unix_permissions and syno_user_add_to_legacy_group
  mk/spksrc.service.installer
Labels: framework

#3163 Sonarr and Radarr fixes
  spk/radarr/src/service-setup.sh
  spk/radarr/src/wizard/install_uifile
  spk/radarr/src/wizard/install_uifile_fre
  spk/radarr/src/wizard/upgrade_uifile
  spk/radarr/src/wizard/upgrade_uifile_fre
  spk/sonarr/src/service-setup.sh
  spk/sonarr/src/wizard/install_uifile
  spk/sonarr/src/wizard/install_uifile_fre
  spk/sonarr/src/wizard/upgrade_uifile
  spk/sonarr/src/wizard/upgrade_uifile_fre
Labels: status/needs-review

#3120 Wizard french translations and permissions handling for NZBGet
  spk/nzbget/src/service-setup.sh
  spk/nzbget/src/wizard/install_uifile
  spk/nzbget/src/wizard/install_uifile_fre
  spk/nzbget/src/wizard/upgrade_uifile
  spk/nzbget/src/wizard/upgrade_uifile_fre
Labels: status/to-publish

#3065 Update SABnzbd to use Generic service and version 2.3.2
  cross/p7zip/Makefile
  cross/p7zip/digests
  cross/p7zip/patches/001-CVE-2016-2334.patch
  cross/p7zip/patches/001-install-not-edit-permissions.patch
  cross/p7zip/patches/002-CVE-2016-2335.patch
  cross/par2cmdline/Makefile
  cross/par2cmdline/digests
  cross/sabnzbd/Makefile
  cross/sabnzbd/digests
  spk/sabnzbd/Makefile
  spk/sabnzbd/src/app/config
  spk/sabnzbd/src/conf/privilege
  spk/sabnzbd/src/dsm-control.sh
  spk/sabnzbd/src/installer.sh
  spk/sabnzbd/src/requirements.txt
  spk/sabnzbd/src/sabnzbd.sc
  spk/sabnzbd/src/service-setup.sh
  spk/sabnzbd/src/wizard/install_uifile
  spk/sabnzbd/src/wizard/install_uifile_enu
  spk/sabnzbd/src/wizard/install_uifile_fre
  spk/sabnzbd/src/wizard/upgrade_uifile
  spk/sabnzbd/src/wizard/upgrade_uifile_enu
  spk/sabnzbd/src/wizard/upgrade_uifile_fre
Labels: status/needs-review

#3097 NzbHydra - Generic Service approach
  spk/nzbhydra/Makefile
  spk/nzbhydra/src/app/config
  spk/nzbhydra/src/conf/privilege
  spk/nzbhydra/src/dsm-control.sh
  spk/nzbhydra/src/installer.sh
  spk/nzbhydra/src/nzbhydra.sc
  spk/nzbhydra/src/service-setup.sh
Labels: status/ready-to-merge, status/to-publish

#3165 Add permissions for "administrators" group to Linux-permissions folders
  mk/spksrc.service.installer
Labels: status/needs-review

#3154 mono: relocate special folders
  native/mono/patches/001-relocate-specialfolders.patch
  spk/mono/Makefile
  spk/mono/src/dsm-control.sh
  spk/mono/src/installer.sh
  spk/mono/src/service-setup.sh
Labels: status/to-publish

#3181 Main share also needs administrators-permissions
  mk/spksrc.service.installer
Labels: framework

#3123 Service Support: add background command execution
  mk/spksrc.service.mk
  mk/spksrc.service.start-stop-daemon
  mk/spksrc.service.start-stop-status
  mk/spksrc.spk.mk
  spk/demoservice/Makefile
  spk/demoservice/src/service-setup.sh
  spk/jackett/Makefile
  spk/mosquitto/Makefile
  spk/radarr/Makefile
  spk/radarr/src/service-setup.sh
  spk/sonarr/Makefile
  spk/sonarr/src/service-setup.sh
Labels: framework

#3144 Transmission 2.93 and Generic Service approach
  cross/transmission/Makefile
  cross/transmission/digests
  cross/transmission/patches/001-no-debug.patch
  spk/transmission/Makefile
  spk/transmission/src/app/config
  spk/transmission/src/conf/privilege
  spk/transmission/src/dsm-control.sh
  spk/transmission/src/installer.sh
  spk/transmission/src/service-setup.sh
  spk/transmission/src/transmission.sc
  spk/transmission/src/wizard/install_uifile
  spk/transmission/src/wizard/install_uifile_enu
  spk/transmission/src/wizard/install_uifile_fre
  spk/transmission/src/wizard/upgrade_uifile
  spk/transmission/src/wizard/upgrade_uifile_enu
  spk/transmission/src/wizard/upgrade_uifile_fre
Labels: status/ready-to-merge, status/to-publish
