Repository SynoCommunity/spksrc, pull requests merged in 2018-07, with the labels that each got.

#3356 Lidarr
  cross/libzen/digests
  cross/lidarr/Makefile
  cross/lidarr/PLIST
  cross/lidarr/digests
  spk/lidarr/Makefile
  spk/lidarr/src/config.xml
  spk/lidarr/src/lidarr.png
  spk/lidarr/src/service-setup.sh
  spk/lidarr/src/wizard/install_uifile
  spk/lidarr/src/wizard/install_uifile_fre
  spk/lidarr/src/wizard/upgrade_uifile
  spk/lidarr/src/wizard/upgrade_uifile_fre
Labels: status/ready-to-merge, status/to-publish

#3292 New package: dante-sockd-1.4.2
  cross/dante-sockd/Makefile
  cross/dante-sockd/PLIST
  cross/dante-sockd/digests
  spk/dante-sockd/Makefile
  spk/dante-sockd/PLIST
  spk/dante-sockd/src/dante.png
  spk/dante-sockd/src/service-setup.sh
  spk/dante-sockd/src/sockd.conf
  spk/dante-sockd/src/wizard/install_uifile
Labels: status/ready-to-merge, status/to-publish, translation

#3371 framework: fix TC_OS_MIN_VER declaration
  mk/spksrc.tc.mk
Labels: status/ready-to-merge

#3378 zsh: use generic installer support
  spk/zsh-static/Makefile
  spk/zsh/Makefile
  spk/zsh/src/dsm-control.sh
  spk/zsh/src/installer.sh
  spk/zsh/src/service-setup.sh
Labels: status/ready-to-merge

#3383 toolchains: fix SRM firmware and digests to publish
  toolchains/syno-ipq806x-1.1/Makefile
  toolchains/syno-northstarplus-1.1/Makefile
  toolchains/syno-northstarplus-1.1/digests
Labels: status/ready-to-merge

#3390 framework: fix busybox start-stop-daemon support for service
  mk/spksrc.service.call_func
  mk/spksrc.service.config
  mk/spksrc.service.mk
  mk/spksrc.service.non-startable
  mk/spksrc.service.privilege-startasroot
  mk/spksrc.service.start-stop-daemon
  mk/spksrc.service.start-stop-status
  mk/spksrc.service.testcase
Labels: status/ready-to-merge
