Repository SynoCommunity/spksrc, pull requests merged in 2018-03, with the labels that each got.

#3178 sslh - Generic Service approach and update to 1.18
  cross/libconfig/Makefile
  cross/libconfig/PLIST
  cross/libconfig/digests
  cross/sslh/Makefile
  cross/sslh/digests
  spk/sslh/Makefile
  spk/sslh/src/dsm-control.sh
  spk/sslh/src/installer.sh
  spk/sslh/src/service-setup.sh
Labels: status/needs-review

#3153 Deluge Generic Service approach
  spk/deluge/Makefile
  spk/deluge/src/app/config
  spk/deluge/src/conf/privilege
  spk/deluge/src/deluge.sc
  spk/deluge/src/dsm-control.sh
  spk/deluge/src/installer.sh
  spk/deluge/src/service-setup.sh
  spk/deluge/src/wizard/install_uifile
  spk/deluge/src/wizard/install_uifile_enu
  spk/deluge/src/wizard/upgrade_uifile
  spk/deluge/src/wizard/upgrade_uifile_enu
Labels: status/to-publish, translation

#3197 Validate digests
  cross/dnscrypt/Makefile
  cross/dnscrypt/digests
  cross/dtach/digests
  cross/glib/digests
  cross/mc/digests
  cross/ncurses/digests
  cross/ncursesw/digests
  cross/p7zip/digests
  cross/par2cmdline/digests
  cross/pcre/digests
  mk/spksrc.checksum.mk
  mk/spksrc.tc.mk
  native/glib/digests
Labels: framework, status/ready-to-merge

#3182 Mylar - Generic Service approach
  spk/mylar/Makefile
  spk/mylar/src/app/config
  spk/mylar/src/conf/privilege
  spk/mylar/src/dsm-control.sh
  spk/mylar/src/installer.sh
  spk/mylar/src/mylar.sc
  spk/mylar/src/service-setup.sh
  spk/mylar/src/wizard/install_uifile
  spk/mylar/src/wizard/install_uifile_enu
  spk/mylar/src/wizard/upgrade_uifile
  spk/mylar/src/wizard/upgrade_uifile_enu
Labels: status/to-publish, translation

#3173 New package cleanup
  cross/dobby/Makefile
  cross/dobby/PLIST
  cross/dobby/digests
  cross/enum34/Makefile
  cross/enum34/PLIST
  cross/enum34/digests
  cross/espeak/Makefile
  cross/espeak/PLIST
  cross/espeak/digests
  cross/flex/Makefile
  cross/flex/PLIST
  cross/flex/digests
  cross/flite/Makefile
  cross/flite/PLIST
  cross/flite/digests
  cross/flite/patches/exactly.patch
  cross/flite/patches/shlib_deps.patch
  cross/guile/Makefile
  cross/guile/digests
  cross/newznab/Makefile
  cross/newznab/PLIST
  cross/newznab/digests
  cross/virtualenv/Makefile
  cross/virtualenv/PLIST
  cross/virtualenv/digests
  cross/yenc/Makefile
  cross/yenc/PLIST
  cross/yenc/digests
  native/guile/Makefile
  native/guile/digests
Labels: repo

#3232 Fix start-stop-status default status wait timeout
  mk/spksrc.service.start-stop-status
Labels: framework
