Repository SynoCommunity/spksrc, pull requests merged in 2018-05, with the labels that each got.

#3302 Fix wizard packaging and various package wizards
  mk/spksrc.spk.mk
  spk/sabnzbd/Makefile
  spk/sabnzbd/src/wizard/upgrade_uifile_fre
  spk/transmission/Makefile
  spk/transmission/src/wizard/install_uifile_fre
  spk/transmission/src/wizard/upgrade_uifile_fre
  spk/tvheadend/src/wizard/install_uifile
  spk/tvheadend/src/wizard/install_uifile_fre
  spk/tvheadend/src/wizard/upgrade_uifile
  spk/tvheadend/src/wizard/upgrade_uifile_fre
Labels: status/ready-to-merge

#3281 Refactor rsnapshot as no-arch
  cross/rsnapshot/Makefile
  mk/spksrc.service.installer
  spk/rsnapshot/Makefile
  spk/rsnapshot/src/dsm-control.sh
  spk/rsnapshot/src/installer.sh
  spk/rsnapshot/src/service-setup.sh
Labels: status/to-publish

#3265 Add DNScrypt-proxy v2.0.10
  cross/dnscrypt-proxy/Makefile
  cross/dnscrypt-proxy/PLIST
  cross/dnscrypt-proxy/digests
  spk/dnscrypt-proxy/Makefile
  spk/dnscrypt-proxy/PLIST
  spk/dnscrypt-proxy/src/dnscrypt-proxy.png
  spk/dnscrypt-proxy/src/service-setup.sh
  spk/dnscrypt-proxy/src/wizard/install_uifile
Labels: status/to-publish, translation

#3315 transmission: update to 2.94
  cross/transmission/Makefile
  cross/transmission/digests
  spk/transmission/Makefile
  spk/transmission/src/wizard/install_uifile
  spk/transmission/src/wizard/install_uifile_fre
  spk/transmission/src/wizard/upgrade_uifile
  spk/transmission/src/wizard/upgrade_uifile_fre
Labels: status/ready-to-merge

#3305 python 2.7: fix cryptography wheel for ARM
  mk/spksrc.wheel.mk
  spk/python/Makefile
Labels: status/ready-to-merge

#3167 LazyLibrarian - Generic Service approach
  spk/lazylibrarian/Makefile
  spk/lazylibrarian/src/app/config
  spk/lazylibrarian/src/conf/privilege
  spk/lazylibrarian/src/dsm-control.sh
  spk/lazylibrarian/src/installer.sh
  spk/lazylibrarian/src/lazylibrarian.png
  spk/lazylibrarian/src/lazylibrarian.sc
  spk/lazylibrarian/src/service-setup.sh
  spk/lazylibrarian/src/wizard/install_uifile
  spk/lazylibrarian/src/wizard/install_uifile_enu
  spk/lazylibrarian/src/wizard/upgrade_uifile
  spk/lazylibrarian/src/wizard/upgrade_uifile_enu
Labels: status/to-publish, translation

#3330 Update SABnzbd to 2.3.4
  cross/sabnzbd/Makefile
  cross/sabnzbd/digests
  spk/sabnzbd/Makefile
Labels: status/ready-to-merge, status/to-publish

#3132 Update uMurmur to 0.2.17 and for DSM 5+6 generic service use
  cross/protobuf-c/Makefile
  cross/protobuf-c/digests
  cross/umurmur/Makefile
  cross/umurmur/digests
  spk/umurmur/Makefile
  spk/umurmur/src/app/config
  spk/umurmur/src/app/umurmur.cgi.pl
  spk/umurmur/src/conf/umurmur.sc
  spk/umurmur/src/dsm-control.sh
  spk/umurmur/src/gencert.sh
  spk/umurmur/src/installer.sh
  spk/umurmur/src/service-setup.sh
  spk/umurmur/src/umurmur.conf
Labels: status/to-publish, translation

#3180 NZBGet-testing - Generic Service approach
  cross/nzbget-testing/Makefile
  cross/nzbget-testing/PLIST
  cross/nzbget-testing/digests
  spk/nzbget-testing/Makefile
  spk/nzbget-testing/src/app/config
  spk/nzbget-testing/src/conf/privilege
  spk/nzbget-testing/src/dsm-control.sh
  spk/nzbget-testing/src/installer.sh
  spk/nzbget-testing/src/nzbget-testing.sc
  spk/nzbget-testing/src/nzbget.conf
  spk/nzbget-testing/src/nzbget.conf.template
  spk/nzbget-testing/src/service-setup.sh
  spk/nzbget-testing/src/wizard/install_uifile
  spk/nzbget-testing/src/wizard/install_uifile_enu
  spk/nzbget-testing/src/wizard/install_uifile_fre
  spk/nzbget-testing/src/wizard/upgrade_uifile
  spk/nzbget-testing/src/wizard/upgrade_uifile_enu
  spk/nzbget-testing/src/wizard/upgrade_uifile_fre
  spk/nzbget/Makefile
Labels: status/to-publish, translation

#3177 PlexPy - Generic Service support
  spk/plexpy-custom/Makefile
  spk/plexpy-custom/src/app/config
  spk/plexpy-custom/src/conf/privilege
  spk/plexpy-custom/src/dsm-control.sh
  spk/plexpy-custom/src/installer.sh
  spk/plexpy-custom/src/plexpy-custom.sc
  spk/plexpy-custom/src/service-setup.sh
  spk/plexpy-custom/src/wizard/install_uifile
  spk/plexpy-custom/src/wizard/install_uifile_enu
Labels: status/to-publish, translation
