Repository SynoCommunity/spksrc, pull requests merged in 2019-01, with the labels that each got.

#3556 Add syno-manager v1.0 package
  mk/spksrc.spk.mk
  spk/syno-magnet/Makefile
  spk/syno-magnet/digests
  spk/syno-magnet/src/magnet.png
Labels: status/ready-to-merge

#3438 itools: udev rules and mount/umount scripts
  spk/itools/Makefile
  spk/itools/src/39-libimobiledevice.rules
  spk/itools/src/common.py
  spk/itools/src/mounting.py
  spk/itools/src/on-inserted.sh
  spk/itools/src/on-removed.sh
  spk/itools/src/service-setup.sh
  spk/itools/src/umounting.py
Labels: status/ready-to-merge, status/to-publish

#3565 mercurial: update to 4.8.1
  cross/mercurial/Makefile
  cross/mercurial/digests
  spk/mercurial/Makefile
Labels: status/ready-to-merge, status/to-publish

#3559 New package - fritzctl-1.4.23
  cross/fritzctl/Makefile
  cross/fritzctl/PLIST
  cross/fritzctl/digests
  spk/synocli-net/Makefile
  spk/synocli-net/src/service-setup.sh
Labels: status/to-publish

#3566 syno-magnet: Update package location because of renamed package name
  spk/syno-magnet/Makefile
  spk/syno-magnet/PLIST
Labels: status/ready-to-merge, status/to-publish

#3567 One shot spk arch convenience func
  Makefile
Labels: status/ready-to-merge

#3586 framework: mark recently added archs as duplicates
  mk/spksrc.common.mk
Labels: status/ready-to-merge

#3572 Update Jackett to 0.10.589
  cross/jackett/Makefile
  cross/jackett/digests
  spk/jackett/Makefile
Labels: status/ready-to-merge
