Repository SynoCommunity/spksrc, pull requests merged in 2019-02, with the labels that each got.

#3592 framework: add PLIST_TRANSFORM for cross Makefile
  mk/spksrc.cross-cc.mk
Labels: status/ready-to-merge

#3613 Bump bcrypt 3.1.4->3.1.5 to permit homeassistant-0.86.4 to install
  cross/bcrypt/Makefile
  cross/bcrypt/digests
Labels: status/ready-to-merge

#3562 Python-3.5.6->3.6.8: update patches, deps, spk rev
  Makefile
  cross/python3/Makefile
  cross/python3/PLIST
  cross/python3/digests
  cross/python3/patches/001-mimetypes.patch
  cross/python3/patches/002-xcompile.patch
  native/python3/Makefile
  native/python3/digests
  spk/python3/Makefile
  spk/python3/src/requirements.txt
  spk/python3/src/service-setup.sh
Labels: status/ready-to-merge, status/to-publish

#3624 borgbackup: update to 1.1.9 for python 3.6
  cross/borgbackup/Makefile
  cross/borgbackup/digests
  spk/borgbackup/Makefile
  spk/borgbackup/src/requirements.txt
Labels: status/ready-to-merge, status/to-publish

#3632 framework: fix DISTRIB_DIR recursive definition
  mk/spksrc.directories.mk
  mk/spksrc.tc.mk
Labels: status/ready-to-merge

#3172 improve icon generation
  mk/spksrc.icon.mk
  mk/spksrc.spk.mk
  spk/squidguard/Makefile
  spk/wallabag/Makefile
Labels: framework

#3623 Tvheadend 4.2.8 fixes
  cross/dvb-apps/Makefile
  cross/dvb-apps/PLIST
  cross/dvb-apps/digests
  cross/dvb-apps/patches/build-libs-only.patch
  cross/nettle/Makefile
  cross/tvheadend/Makefile
  spk/tvheadend/Makefile
  spk/tvheadend/src/accesscontrol.json
  spk/tvheadend/src/passwd.json
  spk/tvheadend/src/service-setup.sh
  spk/tvheadend/src/wizard/install_uifile
  spk/tvheadend/src/wizard/install_uifile_fre
Labels: status/ready-to-merge, status/to-publish

#3555 Update SABnzbd to 2.3.7
  cross/sabnzbd/Makefile
  cross/sabnzbd/digests
  cross/unrar/Makefile
  spk/sabnzbd/Makefile
Labels: status/ready-to-merge

#3462 homeassistant: update to 0.87.1 and generic installer and service
  cross/gmp/Makefile
  cross/libffi/Makefile
  cross/mpc/Makefile
  cross/mpc/PLIST
  cross/mpc/digests
  cross/mpfr/Makefile
  cross/mpfr/PLIST
  cross/mpfr/digests
  cross/mpfr/patches/001-allpatches-20180731.patch
  spk/homeassistant/Makefile
  spk/homeassistant/src/app/config
  spk/homeassistant/src/conf/privilege
  spk/homeassistant/src/dsm-control.sh
  spk/homeassistant/src/homeassistant.sc
  spk/homeassistant/src/installer.sh
  spk/homeassistant/src/requirements.txt
  spk/homeassistant/src/service-setup.sh
  spk/homeassistant/src/wizard/install_uifile
  spk/homeassistant/src/wizard/install_uifile_enu
  spk/homeassistant/src/wizard/upgrade_uifile
  spk/homeassistant/src/wizard/upgrade_uifile_enu
Labels: status/ready-to-merge, status/to-publish
