Repository SynoCommunity/spksrc, pull requests merged in 2019-07, with the labels that each got.

#3720 Updated Tcl to v8.6.9-3
  cross/tcl/Makefile
  spk/tcl/Makefile
  spk/tcl/PLIST
  spk/tcl/src/service-setup.sh
Labels: status/ready-to-merge

#3711 Update SABnzbd to 2.3.9
  cross/sabnzbd/Makefile
  cross/sabnzbd/digests
  spk/sabnzbd/Makefile
Labels: status/to-publish

#3642 Bump imagemagick to stable version
  cross/imagemagick/Makefile
  cross/imagemagick/digests
  spk/imagemagick/Makefile
Labels: status/ready-to-merge, status/to-publish

#3734 add prometheus node_exporter package
  cross/node-exporter/Makefile
  cross/node-exporter/PLIST
  cross/node-exporter/digests
  spk/node-exporter/Makefile
  spk/node-exporter/PLIST
  spk/node-exporter/src/node-exporter.png
  spk/node-exporter/src/service-setup.sh
Labels: status/ready-to-merge, status/to-publish

#3672 Fix downloads and builds (without package updates)
  cross/c_icap/digests
  cross/dnscrypt/Makefile
  cross/dnscrypt/PLIST
  cross/dnscrypt/digests
  cross/he853/Makefile
  cross/js/Makefile
  cross/libcaca/Makefile
  cross/libusb/Makefile
  cross/linux-pam/Makefile
  cross/linux-pam/PLIST
  cross/linux-pam/digests
  cross/mpd/Makefile
  cross/mpd/digests
  cross/oscam/digests
  cross/pear/digests
  cross/phpmemcachedadmin/Makefile
  cross/phpmemcachedadmin/digests
  cross/polarssl/Makefile
  cross/polarssl/PLIST
  cross/polarssl/digests
  cross/polarssl/patches/makefiles-cflags.patch
  cross/ps3netsrv/Makefile
  cross/ps3netsrv/digests
  cross/sabnzbd-testing/Makefile
  cross/sabnzbd-testing/PLIST
  cross/sabnzbd-testing/digests
  cross/sabnzbd/digests
  cross/squidguard/Makefile
  cross/tt-rss/Makefile
  cross/tt-rss/digests
  cross/unzip/Makefile
  spk/dnscrypt/Makefile
  spk/dnscrypt/PLIST
  spk/dnscrypt/src/dnscrypt.png
  spk/dnscrypt/src/dsm-control.sh
  spk/dnscrypt/src/installer.sh
  spk/icecast/Makefile
  spk/sabnzbd-testing/Makefile
  spk/sabnzbd-testing/PLIST
  spk/sabnzbd-testing/src/CharTranslator.py
  spk/sabnzbd-testing/src/app/config
  spk/sabnzbd-testing/src/conf/privilege
  spk/sabnzbd-testing/src/config.ini
  spk/sabnzbd-testing/src/dsm-control.sh
  spk/sabnzbd-testing/src/installer.sh
  spk/sabnzbd-testing/src/nice_defconfig
  spk/sabnzbd-testing/src/requirements.txt
  spk/sabnzbd-testing/src/sabnzbd-testing.png
  spk/sabnzbd-testing/src/sabnzbd-testing.sc
  spk/sabnzbd-testing/src/wizard/install_uifile
  spk/sabnzbd-testing/src/wizard/install_uifile_enu
  spk/sabnzbd-testing/src/wizard/install_uifile_fre
  spk/sabnzbd-testing/src/wizard/upgrade_uifile
  spk/sabnzbd-testing/src/wizard/upgrade_uifile_enu
Labels: status/ready-to-merge

#3685 Added Node.js v10 package.
  Dockerfile
  cross/nodejs/Makefile
  cross/nodejs/PLIST
  cross/nodejs/digests
  spk/nodejs/Makefile
  spk/nodejs/PLIST
  spk/nodejs/src/node.png
Labels: status/ready-to-merge
