Repository SynoCommunity/spksrc, pull requests merged in 2020-10, with the labels that each got.

#4141 ffmpeg: Intel 2020Q3 driver update
  cross/gmmlib/Makefile
  cross/gmmlib/digests
  cross/intel-media-driver/Makefile
  cross/intel-media-driver/digests
  cross/intel-media-sdk/Makefile
  cross/intel-media-sdk/PLIST
  cross/intel-media-sdk/digests
  cross/libva-utils/Makefile
  cross/libva-utils/digests
  cross/libva/Makefile
  cross/libva/PLIST
  cross/libva/digests
Labels: status/ready-to-merge, status/to-publish

#4143 DSM toolkit mk helper
  .gitignore
  cross/ds.evansport/Makefile
  cross/ffmpeg/Makefile
  cross/lirc-0.8.7/Makefile
  cross/lirc-0.9.0/Makefile
  mk/spksrc.cross-env.mk
  mk/spksrc.cross-go.mk
  mk/spksrc.depend.mk
  mk/spksrc.directories.mk
  mk/spksrc.extract.mk
  mk/spksrc.install-resources.mk
  mk/spksrc.kernel-required.mk
  mk/spksrc.pre-check.mk
  mk/spksrc.toolkit-fix.mk
  mk/spksrc.toolkit-flags.mk
  mk/spksrc.toolkit.mk
  toolkit/syno-evansport-5.2/Makefile
  toolkit/syno-evansport-5.2/digests
  toolkit/syno-evansport-6.1/Makefile
  toolkit/syno-evansport-6.1/digests
  toolkit/syno-evansport-6.2.2/Makefile
  toolkit/syno-evansport-6.2.2/digests
  toolkit/syno-evansport-6.2/Makefile
  toolkit/syno-evansport-6.2/digests
Labels: enhancement, status/needs-review

#4186 geminilake: updates for mono applications lidarr, sonarr, radarr, jackett
  cross/jackett/Makefile
  cross/jackett/digests
  cross/lidarr/Makefile
  cross/lidarr/digests
  cross/openssl/Makefile
  cross/radarr/Makefile
  cross/radarr/digests
  cross/sonarr/Makefile
  cross/sonarr/digests
  cross/wallabag/Makefile
  spk/deluge/src/wizard/install_uifile
  spk/hassio/Makefile
  spk/jackett/Makefile
  spk/lidarr/Makefile
  spk/lidarr/src/wizard/install_uifile
  spk/lidarr/src/wizard/install_uifile_fre
  spk/lidarr/src/wizard/upgrade_uifile
  spk/lidarr/src/wizard/upgrade_uifile_fre
  spk/mono/Makefile
  spk/radarr/Makefile
  spk/radarr/src/wizard/install_uifile
  spk/radarr/src/wizard/install_uifile_fre
  spk/radarr/src/wizard/upgrade_uifile
  spk/radarr/src/wizard/upgrade_uifile_fre
  spk/sonarr/Makefile
  spk/sonarr/src/wizard/install_uifile
  spk/sonarr/src/wizard/install_uifile_fre
  spk/sonarr/src/wizard/upgrade_uifile
  spk/sonarr/src/wizard/upgrade_uifile_fre
Labels: status/ready-to-merge

#4191 mosquitto: update to 1.6.12
  cross/c-ares/Makefile
  cross/libwebsockets/Makefile
  cross/libwebsockets/PLIST
  cross/libwebsockets/digests
  cross/mosquitto/Makefile
  cross/mosquitto/PLIST
  cross/mosquitto/digests
  cross/mosquitto/patches/001-fix-prefix.patch
  cross/mosquitto/patches/002-build-websockets.patch
  cross/mosquitto/patches/ppc853x/002-remove-use_of_unsupported-pthread-functions.patch
  cross/openssl/Makefile
  cross/openssl/PLIST
  mk/spksrc.cross-cmake-env.mk
  mk/spksrc.cross-cmake.mk
  spk/mosquitto/Makefile
  spk/mosquitto/src/mosquitto.conf
  spk/mosquitto/src/mosquitto.png
Labels: status/ready-to-merge

#3967 Add stockfish and "fishnet for lichess"
  cross/stockfish-niklasf/Makefile
  cross/stockfish-niklasf/PLIST
  cross/stockfish-niklasf/digests
  cross/stockfish-niklasf/patches/001_update_Makefile_for_aarch64.patch
  cross/stockfish-webgui/Makefile
  cross/stockfish-webgui/PLIST
  cross/stockfish-webgui/digests
  cross/stockfish/Makefile
  cross/stockfish/PLIST
  cross/stockfish/digests
  cross/stockfish/patches/001_update_Makefile_for_aarch64.patch
  spk/fishnet/Makefile
  spk/fishnet/PLIST
  spk/fishnet/src/fishnet.png
  spk/fishnet/src/fishnet_template.ini
  spk/fishnet/src/requirements.txt
  spk/fishnet/src/service-setup.sh
  spk/stockfish/Makefile
  spk/stockfish/PLIST
  spk/stockfish/src/app/config
  spk/stockfish/src/service-setup.sh
  spk/stockfish/src/start-stop-status.sh
  spk/stockfish/src/stockfish.png
  spk/stockfish/src/webgui-config-template.php
  spk/stockfish/src/wizard/install_uifile
Labels: status/ready-to-merge

#4119 Add salt-minion version 3001.1 package
  cross/busybox/configs/patch
  spk/python3/Makefile
  spk/salt-minion/Makefile
  spk/salt-minion/PLIST
  spk/salt-minion/src/conf/privilege
  spk/salt-minion/src/minion.conf
  spk/salt-minion/src/requirements.txt
  spk/salt-minion/src/rsax931.py.patch
  spk/salt-minion/src/salt-minion.png
  spk/salt-minion/src/service-setup.sh
Labels: status/to-publish

#4200 make all-supported and all-default
  kernel/syno-88f6281-6.2.2/Makefile
  kernel/syno-88f6281-6.2.2/digests
  kernel/syno-88f6281-6.2/Makefile
  kernel/syno-88f6281-6.2/digests
  mk/spksrc.common.mk
  mk/spksrc.download.mk
  mk/spksrc.native-cc.mk
  mk/spksrc.spk.mk
  mk/spksrc.tc-vers.mk
  toolchains/syno-88f6281-6.2.2/Makefile
  toolchains/syno-aarch64-6.2.2/Makefile
  toolchains/syno-aarch64-6.2/Makefile
  toolchains/syno-armv7-6.2.2/Makefile
  toolchains/syno-geminilake-6.2/Makefile
  toolchains/syno-geminilake-6.2/digests
  toolchains/syno-purley-6.2/Makefile
  toolchains/syno-purley-6.2/digests
Labels: enhancement, framework, status/needs-review

#4208 bitlbee: Remove obsolete package
  cross/bitlbee/Makefile
  cross/bitlbee/PLIST
  cross/bitlbee/digests
  spk/bitlbee/Makefile
  spk/bitlbee/PLIST
  spk/bitlbee/src/bitlbee.conf
  spk/bitlbee/src/bitlbee.png
  spk/bitlbee/src/bitlbee.sc
  spk/bitlbee/src/conf/privilege
  spk/bitlbee/src/dsm-control.sh
  spk/bitlbee/src/installer.sh
  spk/bitlbee/src/wizard/install_uifile
  spk/bitlbee/src/wizard/install_uifile_fre
Labels: status/ready-to-merge

#4209 Update & fix build of ruTorrent
  cross/cppunit/Makefile
  cross/cppunit/PLIST
  cross/cppunit/digests
  cross/libmediainfo/Makefile
  cross/libmediainfo/digests
  cross/libtorrent-rakshasa/Makefile
  cross/libtorrent-rakshasa/PLIST
  cross/libtorrent-rakshasa/digests
  cross/libtorrent-rakshasa/patches/001-fix-cross-compile.patch
  cross/libzen/Makefile
  cross/libzen/digests
  cross/mediainfo/Makefile
  cross/mediainfo/digests
  cross/rtorrent/Makefile
  cross/rtorrent/digests
  cross/rtorrent/patches/001-add-building-lib-atomic.patch
  cross/rtorrent/patches/002-fix-configure-cross-compile.patch
  cross/rutorrent/Makefile
  cross/rutorrent/digests
  cross/unzip/Makefile
  cross/unzip/digests
  cross/xmlrpc-c/Makefile
  cross/xmlrpc-c/PLIST
  cross/xmlrpc-c/digests
  cross/xmlrpc-c/patches/001-remove-defaul-env-flags.patch
  spk/mediainfo/Makefile
  spk/rutorrent/Makefile
Labels: status/needs-review

#4219 tc.mk: Force two (2x) digits for version
  mk/spksrc.common.mk
  mk/spksrc.spk.mk
  mk/spksrc.tc-flags.mk
  mk/spksrc.tc-vers.mk
  mk/spksrc.tc.mk
  toolchains/syno-geminilake-6.2/Makefile
  toolchains/syno-geminilake-6.2/digests
  toolchains/syno-purley-6.2/Makefile
  toolchains/syno-purley-6.2/digests
Labels: enhancement, framework, status/ready-to-merge

#3747 FlexGet: update to v3.1.80, use python3 and generic service support
  spk/flexget/Makefile
  spk/flexget/src/conf/privilege
  spk/flexget/src/config.yml
  spk/flexget/src/dsm-control.sh
  spk/flexget/src/installer.sh
  spk/flexget/src/requirements.txt
  spk/flexget/src/service-setup.sh
  spk/flexget/src/wizard/install_uifile
  spk/flexget/src/wizard/upgrade_uifile
Labels: status/ready-to-merge, status/to-publish, update

#4229 SABnzbd 3.1.0 update
  cross/sabnzbd/Makefile
  cross/sabnzbd/digests
  spk/sabnzbd/Makefile
  spk/sabnzbd/src/SabToSyno.py
  spk/sabnzbd/src/requirements.txt
Labels: status/needs-review

#4236 framework: fix make publish-all-* in spk.mk
  mk/spksrc.spk.mk
Labels: bug, framework, status/needs-review
