Repository SynoCommunity/spksrc, pull requests merged in 2020-06, with the labels that each got.

#4016 Add make dependency-list and update github-actions
  .github/actions/build-push-pr.sh
  .github/actions/build-tag.sh
  .github/workflows/build.yml
  Makefile
  cross/comskip/Makefile
  cross/ffmpeg/Makefile
  cross/gmmlib/Makefile
  cross/intel-media-driver/Makefile
  cross/intel-media-sdk/Makefile
  cross/iperf3/Makefile
  cross/iperf3/digests
  cross/lame/Makefile
  cross/libaom/Makefile
  cross/libvpx/Makefile
  cross/lirc-0.8.7/Makefile
  cross/lirc-0.8.7/PLIST
  cross/lirc-0.9.0/Makefile
  cross/lirc-0.9.0/PLIST
  cross/sabnzbd/Makefile
  cross/svt-av1/Makefile
  cross/svt-hevc/Makefile
  cross/tvheadend/Makefile
  cross/x264/Makefile
  cross/x265/Makefile
  mk/spksrc.dependency-tree.mk
  mk/spksrc.install-resources.mk
  mk/spksrc.spk.mk
  spk/lirc/Makefile
  spk/synocli-disk/Makefile
  spk/synocli-file/Makefile
  spk/synocli-monitor/Makefile
  spk/synocli-net/Makefile
Labels: framework, status/ready-to-merge

#4012 Update git to version 2.26.2
  cross/curl/Makefile
  cross/curl/PLIST
  cross/curl/digests
  cross/git/Makefile
  cross/git/PLIST
  cross/git/digests
  cross/git/src/gitconfig
  spk/git/Makefile
Labels: status/ready-to-merge, update

#4005 tvheadend update
  cross/ffmpeg/Makefile
  cross/libhdhomerun/Makefile
  cross/libhdhomerun/digests
  cross/libimagequant/Makefile
  cross/libimagequant/PLIST
  cross/libimagequant/digests
  cross/pcre2/Makefile
  cross/pcre2/PLIST
  cross/pcre2/digests
  cross/pngquant/Makefile
  cross/pngquant/PLIST
  cross/pngquant/digests
  cross/svt-av1/Makefile
  cross/svt-av1/digests
  cross/svt-hevc/Makefile
  cross/svt-hevc/digests
  cross/tvheadend/Makefile
  cross/tvheadend/digests
  spk/ffmpeg/Makefile
  spk/tvheadend/Makefile
Labels: status/ready-to-merge

#4031 ntopng: build fix when using non /spksrc root dir
  cross/ntopng/Makefile
  spk/ntopng/Makefile
Labels: bug, status/needs-review

#4025 ppc853x: libbluray fix and tvheadend marked as unsupported
  cross/libbluray/Makefile
  spk/tvheadend/Makefile
Labels: bug, status/needs-review

#3733 Add ser2net and integrate to synocli-net
  cross/gensio/Makefile
  cross/gensio/PLIST
  cross/gensio/digests
  cross/mosh/PLIST
  cross/nmap/PLIST
  cross/ser2net/Makefile
  cross/ser2net/PLIST
  cross/ser2net/digests
  cross/socat/Makefile
  diyspk/ser2net/Makefile
  diyspk/ser2net/PLIST
  diyspk/ser2net/src/ser2net.png
  spk/synocli-net/Makefile
Labels: status/ready-to-merge

#3998 Add generic cmake helper mk
  cross/chromaprint/Makefile
  cross/gmmlib/Makefile
  cross/intel-media-driver/Makefile
  cross/intel-media-sdk/Makefile
  cross/libaom/Makefile
  cross/libmysqlclient/Makefile
  cross/libwebsockets/Makefile
  cross/soxr/Makefile
  cross/svt-av1/Makefile
  cross/svt-hevc/Makefile
  cross/tvheadend/Makefile
  cross/tvheadend/patches/003-disable-pngquant-testing.patch
  cross/uchardet/Makefile
  cross/umurmur/Makefile
  mk/spksrc.cross-cmake-env.mk
  mk/spksrc.cross-cmake.mk
  mk/spksrc.native-env.mk
Labels: framework, status/ready-to-merge
