Repository SynoCommunity/spksrc, pull requests merged in 2020-12, with the labels that each got.

#4149 homeassistant: add missing wheels
  cross/PyNaCl/Makefile
  cross/PyNaCl/PLIST
  cross/PyNaCl/digests
  cross/cffi/Makefile
  cross/cffi/digests
  cross/cython/Makefile
  cross/cython/PLIST
  cross/cython/digests
  cross/numpy/Makefile
  cross/numpy/PLIST
  cross/numpy/digests
  cross/numpy/patches/ppc853x/001-remove-error-pragma_not_allowed_inside_functions.patch
  cross/poetry/Makefile
  cross/poetry/PLIST
  cross/poetry/digests
  cross/ruamel.yaml/Makefile
  native/python/Makefile
  native/python3/Makefile
  spk/homeassistant/Makefile
  spk/homeassistant/src/homeassistant.png
  spk/homeassistant/src/requirements.txt
  spk/homeassistant/src/service-setup.sh
  spk/homeassistant/src/wizard/install_uifile
  spk/homeassistant/src/wizard/install_uifile_fre
  spk/homeassistant/src/wizard/upgrade_uifile
  spk/homeassistant/src/wizard/upgrade_uifile_fre
Labels: status/ready-to-merge

#4276 Update Radarr to v3
  cross/radarr/Makefile
  cross/radarr/digests
  spk/radarr/Makefile
  spk/radarr/src/service-setup.sh
Labels: status/ready-to-merge

#4316 meson: Add meson to pip3 install
  Dockerfile
Labels: framework, meson

#4318 framework: add ninja-build and fix Debian 10 manual installation doc
  Dockerfile
  README.rst
Labels: meson, status/needs-review

#4307 Add meson + ninja support
  cross/glib/Makefile
  cross/glib/PLIST
  cross/glib/digests
  cross/glib/patches/0002-allow-explicit-disabling-of-tests.patch
  cross/glibmm/Makefile
  cross/glibmm/digests
  cross/libdrm/Makefile
  cross/libdrm/digests
  cross/libsigc++/Makefile
  cross/libsigc++/digests
  cross/pixman/Makefile
  cross/zstd/Makefile
  cross/zstd/PLIST
  cross/zstd/digests
  mk/meson/aarch64.cfg
  mk/meson/armv5.cfg
  mk/meson/armv7.cfg
  mk/meson/armv7l.cfg
  mk/meson/i686.cfg
  mk/meson/ppc.cfg
  mk/meson/x86_64.cfg
  mk/spksrc.cross-meson-env.mk
  mk/spksrc.cross-meson.mk
  mk/spksrc.cross-ninja.mk
  mk/spksrc.native-meson-env.mk
  mk/spksrc.native-meson.mk
  native/glib/Makefile
  native/glib/digests
Labels: framework, meson, status/needs-review
