Repository SynoCommunity/spksrc, pull requests merged in 2020-03, with the labels that each got.

#3896 Allow arch-specific level patch to mk build
  mk/spksrc.patch.mk
Labels: arch, enhancement, framework, status/ready-to-merge

#3911 Fix build of python module files
  cross/setuptools/Makefile
  cross/setuptools/digests
  cross/wheel/Makefile
  mk/spksrc.python-module.mk
Labels: status/ready-to-merge

#3906 Update beets to v1.4.9 and migrate to Python3
  mk/spksrc.service.call_func
  spk/beets/Makefile
  spk/beets/src/requirements.txt
  spk/beets/src/service-setup.sh
Labels: update

#3809 Inotify tools
  cross/inotify-tools/Makefile
  cross/inotify-tools/PLIST
  cross/inotify-tools/digests
  spk/inotify-tools/Makefile
  spk/inotify-tools/PLIST
  spk/inotify-tools/src/inotify-tools.png
Labels: status/ready-to-merge, status/to-publish

#3915 tvh: update libhdhomerun to 2020 version + fixes
  cross/libhdhomerun/Makefile
  cross/libhdhomerun/PLIST
  cross/libhdhomerun/digests
  cross/tvheadend/Makefile
  cross/tvheadend/patches/ppc853x/ppc853-old-gcc.patch
  spk/tvheadend/Makefile
Labels: status/needs-review

#3923 Update mutt and add SASL support
  cross/cyrus-sasl/Makefile
  cross/cyrus-sasl/PLIST
  cross/cyrus-sasl/digests
  cross/cyrus-sasl/patches/001_use-host-gcc-to-fix-cross-compile-makemd5.patch
  cross/mutt/Makefile
  cross/mutt/PLIST
  cross/mutt/digests
  cross/mutt/patches/001-not-build-doc.patch
  cross/mutt/patches/001_not-build-doc.patch
  spk/mutt/Makefile
  spk/mutt/src/dsm-control.sh
  spk/mutt/src/installer.sh
  spk/mutt/src/service-setup.sh
Labels: status/ready-to-merge, update

#3894 Update adminer to v4.7.6
  cross/adminer/Makefile
  cross/adminer/PLIST
  cross/adminer/digests
  cross/adminer/patches/001-not-use-pgsql-extension.patch
  spk/adminer/Makefile
  spk/adminer/src/dot-htaccess
  spk/adminer/src/installer.sh
  spk/adminer/src/wizard/install_uifile
  spk/adminer/src/wizard/upgrade_uifile
Labels: status/ready-to-merge, status/to-publish, update
