Repository SynoCommunity/spksrc, pull requests merged in 2020-09, with the labels that each got.

#4160 python3: update to use ncursesw instead of ncurses
  cross/python3/Makefile
  spk/python3/Makefile
Labels: status/to-publish

#4154 Update SABnzbd to 3.0.2
  cross/sabnzbd/Makefile
  cross/sabnzbd/digests
  spk/sabnzbd/Makefile
Labels: status/needs-review, status/to-publish

#4179 Wallabag: Update Wallabag to 2.3.8 and various fixes
  cross/wallabag/Makefile
  cross/wallabag/digests
  spk/wallabag/Makefile
  spk/wallabag/src/dsm-control.sh
  spk/wallabag/src/parameters.yml
  spk/wallabag/src/service-setup.sh
  spk/wallabag/src/wizard/install_uifile
Labels: status/needs-review, update
