Repository SynoCommunity/spksrc, pull requests merged in 2020-01, with the labels that each got.

#3829 Update git
  cross/git/Makefile
  cross/git/digests
  spk/git/Makefile
  spk/git/src/service-setup.sh
Labels: status/ready-to-merge

#3839 Remove busybox dependency for Redis
  spk/redis/Makefile
Labels: status/to-publish

#3842 Ffmpeg intel quick sync
  cross/ffmpeg/Makefile
  cross/ffmpeg/patches/006-fix-MSDK-initialization-failure-in-system-memory-mode.patch
  cross/gmmlib/Makefile
  cross/gmmlib/PLIST
  cross/gmmlib/digests
  cross/intel-media-driver/Makefile
  cross/intel-media-driver/PLIST
  cross/intel-media-driver/digests
  cross/intel-media-driver/patches/001-gcc493-fix.patch
  cross/intel-media-sdk/Makefile
  cross/intel-media-sdk/PLIST
  cross/intel-media-sdk/digests
  cross/intel-vaapi-driver/Makefile
  cross/intel-vaapi-driver/digests
  cross/libdrm/Makefile
  cross/libdrm/PLIST
  cross/libva/Makefile
  cross/libva/PLIST
  cross/libva/digests
  spk/ffmpeg/Makefile
Labels: enhancement, status/ready-to-merge, status/to-publish

#3754 Tvheadend 4.3 dev
  cross/dvb-apps/digests
  cross/libhdhomerun/Makefile
  cross/libhdhomerun/digests
  cross/tvheadend/Makefile
  cross/tvheadend/digests
  cross/tvheadend/patches/000-fix-version.patch
  cross/tvheadend/patches/002-configure-vaapi.patch
  spk/tvheadend/Makefile
Labels: status/ready-to-merge

#3857 comskip: update to 0.82.010
  cross/comskip/Makefile
  cross/comskip/digests
  spk/chromaprint/Makefile
  spk/comskip/Makefile
  spk/ffmpeg/Makefile
Labels: status/ready-to-merge

#3858 mediainfo: update to 19.09
  cross/libmediainfo/Makefile
  cross/libmediainfo/digests
  cross/mediainfo/Makefile
  cross/mediainfo/digests
  spk/mediainfo/Makefile
Labels: status/ready-to-merge
