Repository SynoCommunity/spksrc, pull requests merged in 2020-08, with the labels that each got.

#4027 syncthing: Incorporate upstream release v1.7.1.
  cross/syncthing/Makefile
  cross/syncthing/digests
  spk/syncthing/Makefile
Labels: status/ready-to-merge, status/to-publish

#4060 Icecast: add taglib to support ID3 tags (#4059)
  cross/ezstream/Makefile
  cross/taglib/Makefile
  cross/taglib/PLIST
  cross/taglib/digests
  spk/icecast/Makefile
  spk/icecast/src/icecast.png
Labels: enhancement, status/ready-to-merge, status/to-publish

#4066 update curl to fix usage of ca certificates
  .github/actions/build.sh
  .github/actions/build_status.sh
  cross/curl/Makefile
  cross/curl/PLIST
  cross/curl/digests
  cross/libtorrent-rakshasa/Makefile
  cross/rtorrent/Makefile
  mk/spksrc.common.mk
  mk/spksrc.cross-cmake-env.mk
  spk/domoticz/Makefile
  spk/git/Makefile
  spk/jackett/Makefile
  spk/lidarr/Makefile
  spk/ntopng/Makefile
  spk/python/Makefile
  spk/python3/Makefile
  spk/radarr/Makefile
  spk/rutorrent/Makefile
  spk/rutorrent/src/.rtorrent.rc
  spk/rutorrent/src/installer.sh
  spk/sonarr/Makefile
  spk/transmission/Makefile
Labels: status/ready-to-merge

#3953 [python3] Upgrade to 3.7.7 + homeassistant build fixes
  cross/bcrypt/Makefile
  cross/cffi/Makefile
  cross/python3/Makefile
  cross/python3/digests
  cross/python3/patches/005-configure.ac-libffi.patch
  cross/python3/patches/ppc853x/006-configure-fix-autodetection-for-unused-result.patch
  mk/spksrc.common.mk
  mk/spksrc.python-module.mk
  mk/spksrc.python-wheel.mk
  mk/spksrc.wheel.mk
  native/python3/Makefile
  native/python3/digests
  spk/borgbackup/Makefile
  spk/homeassistant/Makefile
  spk/homeassistant/src/requirements.txt
  spk/python3/Makefile
  spk/rdiff-backup/Makefile
Labels: status/to-publish

#4103 chromaprint build fix
  cross/chromaprint/Makefile
  mk/spksrc.cross-cmake-env.mk
  spk/chromaprint/Makefile
  spk/comskip/Makefile
  spk/ffmpeg/Makefile
  spk/tvheadend/Makefile
Labels: status/needs-review, status/ready-to-merge, status/to-publish

#4033 ffmpeg: update to 4.3.1
  cross/ffmpeg/Makefile
  cross/ffmpeg/PLIST
  cross/ffmpeg/digests
  cross/ffmpeg/patches/001-replace-arch-env-by-ffmpeg_arch.patch
  cross/ffmpeg/patches/002-tvheadend-ffmpeg.libx264.patch
  cross/ffmpeg/patches/003-tvheadend-ffmpeg.libx265.patch
  cross/ffmpeg/patches/003-tvheadend-ffmpeg.vaapi_encode.patch
  cross/ffmpeg/patches/004-Add-ability-for-ffmpeg-to-run-svt-hevc.patch
  cross/ffmpeg/patches/005-Add-ability-for-ffmpeg-to-run-svt-av1.patch
  cross/ffmpeg/patches/005-fix-MSDK-initialization-failure-in-system-memory-mode.patch
  cross/ffmpeg/patches/020-SYNO-videostation-hls-seek-time.patch
  cross/ffmpeg/patches/021-SYNO-videostation-hls-costumized-ts-name.patch
  cross/ffmpeg/patches/022-SYNO-videostation-skip-displaymatrix.patch
  cross/ffmpeg/patches/023-SYNO-videostation-webm-seek-time.patch
  cross/ffmpeg/patches/030-SYNO-smooth-streaming.patch
  cross/ffmpeg/patches/033-SYNO-write-riff-info-tag-to-wav.patch
  cross/ffmpeg/patches/alpine/001-SYNO-alpine-neon-libwscale.patch
  cross/ffmpeg/patches/evansport/001-SYNO-evansport-hwaccels.patch
  cross/ffmpeg/patches/evansport/002-SYNO-evansport-auto-hw-decoder.patch
  cross/ffmpeg/patches/evansport/003-SYNO-evansport-flv-extradata.patch
  cross/gmmlib/Makefile
  cross/gmmlib/digests
  cross/intel-media-driver/Makefile
  cross/intel-media-driver/digests
  cross/intel-media-driver/patches/001-std_c++11.patch
  cross/intel-media-driver/patches/002-fix-error_array_used_as_initializer-PerfUtility.patch.DISABLE
  cross/intel-media-driver/patches/003-fix-error_MOS_Delete_void.patch
  cross/intel-media-sdk/Makefile
  cross/intel-media-sdk/PLIST
  cross/intel-media-sdk/digests
  cross/intel-media-sdk/patches/001-gcc493-fix-TEBMap-TEBIt-protected-to-public.patch
  cross/intel-vaapi-driver/Makefile
  cross/intel-vaapi-driver/digests
  cross/libaom/Makefile
  cross/libaom/digests
  cross/libva-utils/Makefile
  cross/libva-utils/digests
  cross/libva/Makefile
  cross/libva/PLIST
  cross/libva/digests
  cross/libzmq/Makefile
  cross/libzmq/PLIST
  cross/libzmq/digests
  cross/svt-av1/Makefile
  cross/svt-av1/PLIST
  cross/svt-av1/digests
  cross/svt-hevc/Makefile
  cross/svt-hevc/digests
  cross/x265/Makefile
  cross/x265/PLIST
  cross/x265/digests
  cross/x265/patches/aarch64/001-aarch64-build-fix.patch
  spk/ffmpeg/Makefile
Labels: status/ready-to-merge, status/to-publish

#4126 ffmpeg: Fix a build issue with libshine caused by endif
  cross/ffmpeg/Makefile
  cross/libbluray/Makefile
  spk/ffmpeg/Makefile
Labels: bug

#4035 Update SABnzbd to 3.0.1 and Python 3
  cross/sabnzbd/Makefile
  cross/sabnzbd/digests
  spk/sabnzbd/Makefile
  spk/sabnzbd/src/CharTranslator.py
  spk/sabnzbd/src/requirements.txt
  spk/sabnzbd/src/service-setup.sh
Labels: status/ready-to-merge

#4139 chromaprint: Fix using shared libraries
  cross/chromaprint/PLIST
  spk/chromaprint/Makefile
Labels: bug, status/needs-review, status/ready-to-merge, status/to-publish

#4129 libvpx: Fix DSM-5.2 builds
  cross/ffmpeg/Makefile
  cross/gmp/Makefile
  cross/libvpx/patches/88f6281-6.1/001-gcc-over-ld-configure-fix.patch
  cross/libvpx/patches/DSM-5.2/001-gcc-over-ld-configure-fix.patch
  mk/spksrc.patch.mk
Labels: arch, enhancement, status/ready-to-merge

#4140 x265: Use github mirror as mercurial url is now dead
  cross/x265/Makefile
  cross/x265/digests
Labels: bug, status/ready-to-merge
