Repository SynoCommunity/spksrc, pull requests merged in 2020-04, with the labels that each got.

#3752 Update ps3netsrv
  cross/ps3netsrv/Makefile
  cross/ps3netsrv/digests
  cross/ps3netsrv/patches/100-makefile.patch
  spk/ps3netsrv/Makefile
Labels: status/work-in-progress

#3865 Update mono
  cross/mono/Makefile
  cross/mono/PLIST
  cross/mono/digests
  cross/mono/patches/002-fix-shm-open-configuration-regression.patch
  native/mono/Makefile
  native/mono/digests
  spk/jackett/Makefile
  spk/jackett/src/service-setup.sh
  spk/lidarr/Makefile
  spk/lidarr/src/service-setup.sh
  spk/mono/Makefile
  spk/mono/src/mono.png
  spk/radarr/Makefile
  spk/radarr/src/service-setup.sh
  spk/sonarr/Makefile
  spk/sonarr/src/service-setup.sh
Labels: status/ready-to-merge, status/to-publish

#3936 Lint and fix json files
  Makefile
  spk/flexget/src/wizard/install_uifile
  spk/flexget/src/wizard/install_uifile_enu
  spk/horde/src/wizard/install_uifile
  spk/horde/src/wizard/install_uifile_enu
  spk/htpcmanager/src/wizard/install_uifile
  spk/htpcmanager/src/wizard/install_uifile_enu
  spk/htpcmanager/src/wizard/install_uifile_fre
  spk/subliminal/src/wizard/install_uifile
  spk/subliminal/src/wizard/install_uifile_enu
Labels: status/ready-to-merge

#3939 Compile and distribute immutables along with Python3
  cross/immutables/Makefile
  cross/immutables/PLIST
  cross/immutables/digests
  spk/python3/Makefile
  spk/python3/src/requirements.txt
Labels: status/ready-to-merge
