Repository SynoCommunity/spksrc, pull requests merged in 2021-09, with the labels that each got.

#4789 DSM7: Set synocommunity as the default group
  mk/spksrc.service.mk
Labels: framework, status/needs-review

#4803 Fix per-arch builds & add multi-arch & single arch parallel builds
  mk/spksrc.common.mk
  mk/spksrc.compile.mk
  mk/spksrc.cross-cc.mk
  mk/spksrc.cross-cmake.mk
  mk/spksrc.cross-env.mk
  mk/spksrc.spk.mk
Labels: framework, status/ready-to-merge

#4849 Use cmake+ninja by default
  cross/libaom/Makefile
  mk/spksrc.cross-cmake-env.mk
  mk/spksrc.cross-cmake.mk
  mk/spksrc.cross-ninja.mk
Labels: framework, status/needs-review

#4854 parallel build: First set of fixes
  cross/busybox/Makefile
  cross/bzip2/Makefile
  cross/dropbear/Makefile
  cross/libaom/Makefile
  cross/lua/Makefile
  cross/mpfr/Makefile
  cross/mtproxy/Makefile
  cross/node-exporter/Makefile
  cross/p7zip/Makefile
  cross/python3/Makefile
  cross/python38/Makefile
  cross/rtorrent/Makefile
  cross/tcp_wrappers/Makefile
  cross/udns/Makefile
  cross/unzip/Makefile
  mk/spksrc.common.mk
  mk/spksrc.compile.mk
  mk/spksrc.cross-cc.mk
  mk/spksrc.cross-cmake-env.mk
  mk/spksrc.cross-cmake.mk
  mk/spksrc.cross-ninja.mk
  mk/spksrc.native-env.mk
  mk/spksrc.spk.mk
  native/python3/Makefile
  native/python38/Makefile
  native/zip/Makefile
Labels: framework, status/needs-review

#4869 add github download action
  .github/actions/build.sh
  .github/actions/download.sh
  .github/actions/prepare.sh
  .github/workflows/build.yml
Labels: framework

#4880 DSM7: split comcerto2k out of generic ARMv7 build due to old glibc
  .github/workflows/build.yml
  mk/spksrc.archs.mk
  toolchain/syno-armv7-6.1/Makefile
  toolchain/syno-armv7-7.0/Makefile
Labels: framework
