Repository SynoCommunity/spksrc, pull requests merged in 2021-06, with the labels that each got.

#4652 Fix dsm7 service setup
  mk/spksrc.service.installer.dsm5
  mk/spksrc.service.installer.dsm6
  mk/spksrc.service.mk
Labels: framework

#4682 uriparser: Update from broken 0.91 to version 0.95 and use cmake
  cross/uriparser/Makefile
  cross/uriparser/PLIST
  cross/uriparser/digests
Labels: bug, status/needs-review

#4685 syncthing: update to v1.17.0
  cross/syncthing/Makefile
  cross/syncthing/digests
  spk/syncthing/Makefile
  spk/syncthing/src/config.xml
  spk/syncthing/src/service-setup.sh
  spk/syncthing/src/syncthing.png
  spk/syncthing/src/wizard/install_uifile
  spk/syncthing/src/wizard/install_uifile_fre
  spk/syncthing/src/wizard/upgrade_uifile
  spk/syncthing/src/wizard/upgrade_uifile_fre
Labels: update

#4674 Update domoticz to v2020.2
  cross/boost/Makefile
  cross/boost/PLIST
  cross/boost/digests
  cross/c-ares/Makefile
  cross/c-ares/PLIST
  cross/c-ares/digests
  cross/cereal/Makefile
  cross/cereal/PLIST
  cross/cereal/digests
  cross/cereal/patches/001-do-not-build-tests-and-doc.patch
  cross/domoticz/Makefile
  cross/domoticz/PLIST
  cross/domoticz/digests
  cross/domoticz/patches/001-make-version-configurable.patch
  cross/jsoncpp/Makefile
  cross/jsoncpp/PLIST
  cross/jsoncpp/digests
  cross/mosquitto/Makefile
  cross/mosquitto/digests
  cross/openzwave/Makefile
  cross/openzwave/PLIST
  cross/openzwave/digests
  mk/spksrc.cross-cmake-env.mk
  native/cmake/Makefile
  native/cmake/digests
  spk/domoticz/Makefile
  spk/domoticz/src/conf/privilege
  spk/domoticz/src/domoticz.sc
  spk/domoticz/src/dsm-control.sh
  spk/domoticz/src/installer.sh
  spk/domoticz/src/service-setup.sh
  spk/mosquitto/Makefile
  spk/mosquitto/src/service-setup.sh
Labels: update

#4576 FFMPEG Udpate to version 4.3.2
  cross/ffmpeg/Makefile
  cross/ffmpeg/digests
  cross/ffmpeg/patches/010-jellyfin-fix-segment-muxer.patch
  cross/ffmpeg/patches/x64/001-jellyfin-lavfi-add-a-filter-for-uploading-normal-frames-to-VAAPI.patch
  cross/ffmpeg/patches/x64/002-jellyfin-fix-for-the-broken-tonemap_vaapi-filter.patch
  cross/flac/Makefile
  cross/flac/digests
  cross/gmmlib/Makefile
  cross/gmmlib/PLIST
  cross/gmmlib/digests
  cross/intel-media-driver/Makefile
  cross/intel-media-driver/digests
  cross/intel-media-sdk/Makefile
  cross/intel-media-sdk/PLIST
  cross/intel-media-sdk/digests
  cross/libaom/Makefile
  cross/libaom/PLIST
  cross/libaom/digests
  cross/libbluray/Makefile
  cross/libbluray/PLIST
  cross/libbluray/digests
  cross/libdrm/Makefile
  cross/libdrm/PLIST
  cross/libdrm/PLIST.auto
  cross/libdrm/digests
  cross/libva-utils/Makefile
  cross/libva-utils/digests
  cross/libva/Makefile
  cross/libva/PLIST
  cross/libva/digests
  cross/libvpx/Makefile
  cross/libvpx/PLIST
  cross/libvpx/digests
  cross/svt-av1/Makefile
  cross/svt-av1/PLIST
  cross/svt-av1/digests
  cross/svt-av1/patches/aarch64/0001-Fix-C-only-build.patch
  cross/svt-hevc/Makefile
  cross/svt-hevc/digests
  cross/util-linux/Makefile
  cross/util-linux/digests
  cross/x264/Makefile
  cross/x264/digests
  cross/x265/Makefile
  cross/x265/PLIST
  cross/x265/digests
  spk/ffmpeg/Makefile
Labels: status/needs-review

#3883 synocli-file: add ripgrep, initial rust support
  cross/ripgrep/Makefile
  cross/ripgrep/PLIST
  cross/ripgrep/digests
  diyspk/ripgrep/Makefile
  diyspk/ripgrep/PLIST
  diyspk/ripgrep/src/ripgrep.png
  mk/spksrc.cross-rust.mk
  spk/synocli-file/Makefile
Labels: build/rust, update
