Repository SynoCommunity/spksrc, pull requests merged in 2021-04, with the labels that each got.

#4512 Remove utf8 wrappers
  cross/mutt/Makefile
  cross/mutt/PLIST
  cross/mutt/digests
  cross/tmux/Makefile
  cross/tmux/PLIST
  cross/tmux/src/tmux-utf8
  cross/vim/Makefile
  cross/vim/PLIST
  spk/mutt/Makefile
  spk/mutt/src/mutt-utf8
  spk/synocli-net/Makefile
  spk/vim/Makefile
  spk/vim/src/vim-utf8
Labels: status/ready-to-merge

#4535 DSM6: Keep previous behaviour and assume no file by default
  mk/spksrc.service.mk
Labels: bug, framework, status/ready-to-merge

#4494 Fishshell: Fix DSM7 build
  cross/fish/Makefile
  cross/fish/digests
  cross/fish/patches/arm-7.0/001-cmake-remove-gold-linker.patch
  spk/fish/Makefile
  spk/fish/src/service-setup.sh
Labels: dsm 7.0, status/needs-review

#4556 Add $SYNOPKG_PKGVAR backwards compatibility to start-stop-status
  mk/spksrc.service.start-stop-daemon
  mk/spksrc.service.start-stop-status
Labels: dsm 6.0, dsm 7.0, framework

#4549 fix build and update rsnapshot
  cross/rsnapshot/Makefile
  cross/rsnapshot/PLIST
  cross/rsnapshot/digests
  spk/rsnapshot/Makefile
Labels: update

#4537 Update SABnzbd to 3.2.1
  cross/sabnzbd/Makefile
  cross/sabnzbd/digests
  cross/sabnzbd/patches/001-disable_new_version_check.patch
  spk/sabnzbd/Makefile
  spk/sabnzbd/src/requirements.txt
  spk/sabnzbd/src/service-setup.sh
Labels: status/ready-to-merge

#4527 syncthing: Upgrade to v1.15.1 and ignore folder permissions by default.
  cross/syncthing/Makefile
  cross/syncthing/digests
  mk/spksrc.service.start-stop-status
  spk/syncthing/Makefile
  spk/syncthing/src/config.xml
  spk/syncthing/src/options.conf
  spk/syncthing/src/service-setup.sh
Labels: status/ready-to-merge

#3932 Add Jellyfin (BETA)
  cross/jellyfin-web/Makefile
  cross/jellyfin-web/PLIST
  cross/jellyfin-web/digests
  cross/jellyfin/Makefile
  cross/jellyfin/PLIST
  cross/jellyfin/digests
  native/nodejs/Makefile
  native/nodejs/digests
  spk/jellyfin/Makefile
  spk/jellyfin/PLIST
  spk/jellyfin/src/app/config
  spk/jellyfin/src/conf/resource
  spk/jellyfin/src/jellyfin.png
  spk/jellyfin/src/service-setup.sh
  spk/jellyfin/src/wizard/install_uifile
Labels: dotnet, status/needs-review

#4566 Enhance checksum verification for multiple files
  cross/libstdc++/Makefile
  cross/libstdc++/digests
  cross/lidarr/Makefile
  cross/lidarr/digests
  cross/lidarr/digests_dir/arm
  cross/lidarr/digests_dir/arm64
  cross/lidarr/digests_dir/x64
  cross/radarr/Makefile
  cross/radarr/digests
  cross/radarr/digests_dir/arm
  cross/radarr/digests_dir/arm64
  cross/radarr/digests_dir/x64
  mk/spksrc.checksum.mk
  spk/lidarr/Makefile
  spk/lidarr/PLIST
Labels: framework, status/ready-to-merge

#4514 Update adminer
  cross/adminer/Makefile
  cross/adminer/digests
  mk/spksrc.spk.mk
  spk/adminer/Makefile
  spk/adminer/src/conf/resource
  spk/adminer/src/dot-htaccess-apache2.2
  spk/adminer/src/dot-htaccess-apache2.4
  spk/adminer/src/installer.sh
Labels: status/ready-to-merge

#4569 create sharper package icons
  mk/spksrc.spk.mk
  spk/bicbucstriim/src/bicbucstriim.png
  spk/borgbackup/src/borgbackup.png
  spk/gentoo-chroot/src/gentoo.png
  spk/imagemagick/src/imagemagick.png
  spk/maraschino/src/maraschino.png
  spk/minio/src/minio.png
  spk/monit/src/monit.png
Labels: framework

#4571 update flexget to resolve security issues
  spk/flexget/Makefile
  spk/flexget/src/requirements.txt
  spk/flexget/src/service-setup.sh
Labels: status/ready-to-merge

#4575 generic solution for multifile digests (followup of #4566)
  cross/libstdc++/Makefile
  cross/lidarr/Makefile
  cross/radarr/Makefile
  mk/spksrc.download.mk
  mk/spksrc.generate-digests.mk
  mk/spksrc.install-resources.mk
Labels: framework
