Repository SynoCommunity/spksrc, pull requests merged in 2021-08, with the labels that each got.

#4753 Update DSM7.0 Toolchains
  mk/spksrc.tc-flags.mk
  mk/spksrc.tc-vers.mk
  toolchain/syno-aarch64-7.0/Makefile
  toolchain/syno-aarch64-7.0/digests
  toolchain/syno-alpine-7.0/Makefile
  toolchain/syno-alpine-7.0/digests
  toolchain/syno-apollolake-7.0/Makefile
  toolchain/syno-apollolake-7.0/digests
  toolchain/syno-armada370-7.0/Makefile
  toolchain/syno-armada370-7.0/digests
  toolchain/syno-armada375-7.0/Makefile
  toolchain/syno-armada375-7.0/digests
  toolchain/syno-armada38x-7.0/Makefile
  toolchain/syno-armada38x-7.0/digests
  toolchain/syno-armadaxp-7.0/Makefile
  toolchain/syno-armadaxp-7.0/digests
  toolchain/syno-armv7-6.2.4/Makefile
  toolchain/syno-armv7-7.0/Makefile
  toolchain/syno-armv7-7.0/digests
  toolchain/syno-avoton-7.0/Makefile
  toolchain/syno-avoton-7.0/digests
  toolchain/syno-braswell-7.0/Makefile
  toolchain/syno-braswell-7.0/digests
  toolchain/syno-broadwell-7.0/Makefile
  toolchain/syno-broadwell-7.0/digests
  toolchain/syno-broadwellnk-7.0/Makefile
  toolchain/syno-broadwellnk-7.0/digests
  toolchain/syno-bromolow-7.0/Makefile
  toolchain/syno-bromolow-7.0/digests
  toolchain/syno-cedarview-7.0/Makefile
  toolchain/syno-cedarview-7.0/digests
  toolchain/syno-comcerto2k-7.0/digests
  toolchain/syno-denverton-7.0/Makefile
  toolchain/syno-denverton-7.0/digests
  toolchain/syno-evansport-7.0/Makefile
  toolchain/syno-evansport-7.0/digests
  toolchain/syno-geminilake-7.0/Makefile
  toolchain/syno-geminilake-7.0/digests
  toolchain/syno-grantley-7.0/Makefile
  toolchain/syno-grantley-7.0/digests
  toolchain/syno-kvmx64-7.0/Makefile
  toolchain/syno-kvmx64-7.0/digests
  toolchain/syno-monaco-7.0/Makefile
  toolchain/syno-monaco-7.0/digests
  toolchain/syno-purley-7.0/Makefile
  toolchain/syno-purley-7.0/digests
  toolchain/syno-rtd1296-7.0/Makefile
  toolchain/syno-rtd1296-7.0/digests
  toolchain/syno-v1000-7.0/Makefile
  toolchain/syno-v1000-7.0/digests
  toolchain/syno-x64-7.0/Makefile
  toolchain/syno-x64-7.0/digests
Labels: framework

#4782 update deveopment environment
  Dockerfile
  README.rst
Labels: framework

#4781 fix package user in privilege file
  mk/spksrc.service.mk
Labels: framework

#4793 dotnet: mark armadaxp and alpine as unsupported
  mk/spksrc.cross-dotnet-env.mk
  spk/jellyfin/Makefile
  spk/radarr/Makefile
Labels: dotnet

#4580 homeassistant: update to version 2021.8.8
  cross/asyncstdlib/Makefile
  cross/asyncstdlib/PLIST
  cross/asyncstdlib/digests
  cross/numpy/Makefile
  cross/numpy/digests
  cross/numpy/patches/x64/001-fix-auto-detection-of-avx-512f-intrinsics.patch
  cross/pillow/patches/ppc/001-avoid_redefinition_of_typedef_uint32_t.patch
  cross/pycryptodomex/Makefile
  cross/pycryptodomex/PLIST
  cross/pycryptodomex/digests
  mk/spksrc.service.use_alternate_tmpdir
  mk/spksrc.wheel.mk
  spk/homeassistant/Makefile
  spk/homeassistant/src/postinst_components_requirements.txt
  spk/homeassistant/src/postinst_default_config_requirements.txt
  spk/homeassistant/src/requirements.txt
  spk/homeassistant/src/service-setup.sh
Labels: update
