Repository SynoCommunity/spksrc, pull requests merged in 2021-11, with the labels that each got.

#4937 python 3.10.0
  cross/pillow/Makefile
  cross/pillow/digests
  cross/python310/Makefile
  cross/python310/PLIST
  cross/python310/digests
  cross/python310/patches/001-mimetypes.patch
  cross/python310/patches/002-xcompile.patch
  cross/python310/patches/003-rpath.patch
  cross/python310/patches/004-xcompile-paths.patch
  cross/python310/patches/005-configure.ac-libffi.patch
  cross/python310/patches/ppc853x/006-configure-fix-autodetection-for-unused-result.patch
  cross/python310/src/mime.types
  mk/spksrc.archs.mk
  mk/spksrc.common.mk
  mk/spksrc.wheel.mk
  native/python310/Makefile
  native/python310/digests
  spk/python310/Makefile
  spk/python310/PLIST
  spk/python310/src/python3.png
  spk/python310/src/requirements-cross.txt
  spk/python310/src/requirements.txt
  spk/python310/src/service-setup.sh
Labels: status/needs-review

#4920 Sickchill 6 7 rebuild with Py3.8.12-6
  mk/spksrc.common.mk
  mk/spksrc.wheel.mk
  spk/sickchill/Makefile
  spk/sickchill/src/requirements-cross.txt
  spk/sickchill/src/requirements.txt
  spk/sickchill/src/service-setup.sh
  spk/sickchill/src/wizard/install_uifile
  spk/sickchill/src/wizard/upgrade_uifile
Labels: status/ready-to-merge

#4096 update octoprint to v1.7.2 and Python38
  cross/octoprint/Makefile
  cross/octoprint/digests
  cross/octoprint/patches/001-update-depenances.patch
  spk/octoprint/Makefile
  spk/octoprint/src/conf/privilege
  spk/octoprint/src/config.yaml
  spk/octoprint/src/dsm-control.sh
  spk/octoprint/src/installer.sh
  spk/octoprint/src/octoprint.png
  spk/octoprint/src/octoprint.sc
  spk/octoprint/src/requirements-cross.txt
  spk/octoprint/src/requirements.txt
  spk/octoprint/src/service-setup.sh
Labels: update

#4964 SickChill update to fix v3 install errors
  cross/sickchill/Makefile
  cross/sickchill/digests
  cross/sickchill/patches/01-fix-python3.8.patch
  spk/sickchill/Makefile
  spk/sickchill/src/requirements-cross.txt
  spk/sickchill/src/requirements.txt
  spk/sickchill/src/service-setup.sh
Labels: status/ready-to-merge, status/to-publish

#4910 Comply to DSM7 and set as broken
  mk/spksrc.pre-check.mk
  spk/debian-chroot/BROKEN
  spk/gentoo-chroot/BROKEN
  spk/pyload/BROKEN
Labels: framework, status/needs-review
