Repository SynoCommunity/spksrc, pull requests merged in 2021-01, with the labels that each got.

#4356 fix dependency targets
  mk/spksrc.cross-meson-env.mk
  mk/spksrc.dependency-tree.mk
Labels: build/meson, framework

#4386 cross-meson.mk: Fix build issue - conflict commits #4356 #4349
  mk/spksrc.cross-meson-env.mk
Labels: bug, framework

#4383 native/go: Fix build issue when first invoke through cross-build
  native/go/Makefile
  native/go/digests
Labels: bug

#4394 tvheadend: Remove native/python dependency
  cross/tvheadend/Makefile
Labels: status/needs-review, status/ready-to-merge
