Repository SynoCommunity/spksrc, pull requests merged in 2022-10, with the labels that each got.

#5192 Upgrade cops 1.0.1 => 1.1.3 + DSM 7
  cross/cops/Makefile
  cross/cops/digests
  spk/cops/Makefile
  spk/cops/src/conf/PKG_DEPS
  spk/cops/src/conf/resource
  spk/cops/src/dsm-control.sh
  spk/cops/src/installer.sh
  spk/cops/src/service-setup.sh
  spk/cops/src/wizard/fragments/php_configuration_requirements.json
  spk/cops/src/wizard/fragments/php_configuration_requirements_fre.json
  spk/cops/src/wizard/install_uifile
  spk/cops/src/wizard/install_uifile_fre
Labels: status/ready-to-merge

#5441 Docker: Install rustc & upgrade image to Debian 11 bullseye
  Dockerfile
Labels: framework, status/ready-to-merge, build/rust

#5345 Memcached: fix DSM 6 installation procedure
  spk/memcached/Makefile
  spk/memcached/src/service-setup.sh
Labels: status/needs-review

#5466 cross-rust.mk: Fix regular build post PR #5435
  mk/spksrc.cross-rust.mk
Labels: framework, build/rust

#5424 Update toolchains
  mk/spksrc.archs.mk
  toolchain/syno-alpine-4k-6.0.2/Makefile
  toolchain/syno-alpine-4k-6.0.2/digests
  toolchain/syno-r1000-7.1/digests
Labels: framework
