Repository SynoCommunity/spksrc, pull requests merged in 2022-05, with the labels that each got.

#5095 synokernel-cdrom: Package basic cdrom kernel modules
  .github/actions/prepare.sh
  cross/psmisc/Makefile
  cross/psmisc/PLIST
  cross/psmisc/digests
  cross/usbutils/Makefile
  cross/usbutils/PLIST
  cross/usbutils/digests
  mk/spksrc.common.mk
  mk/spksrc.copy.mk
  mk/spksrc.depend.mk
  mk/spksrc.dependency-tree.mk
  mk/spksrc.kernel-required.mk
  mk/spksrc.kernel.mk
  mk/spksrc.pre-check.mk
  mk/spksrc.spk.mk
  spk/synocli-kernel/Makefile
  spk/synocli-kernel/src/SynoPackagegreen-kernel.svg
  spk/synocli-kernel/src/synocli-kernel.png
  spk/synocli-kernel/src/synocli-kernelmodule.sh
  spk/synokernel-cdrom/Makefile
  spk/synokernel-cdrom/PLIST
  spk/synokernel-cdrom/src/synokernel-cdrom.cfg
  spk/synokernel-cdrom/src/synokernel-cdrom.png
  spk/synokernel-cdrom/src/synokernel-cdrom.svg
Labels: framework, status/needs-review

#5248 spk.mk: Fix publishing of kernel-module packages
  mk/spksrc.spk.mk
Labels: bug

#5260 dsm5/6 installer: fix share creation (close #4357)
  mk/spksrc.service.installer.dsm5
  mk/spksrc.service.installer.dsm6
Labels: framework

#5234 borgbackup: Enable llfuse support and package pure-python wheels
  cross/fuse/PLIST
  spk/borgbackup/Makefile
  spk/borgbackup/src/requirements-crossenv.txt
Labels: status/work-in-progress

#5277 ffmpeg extras
  cross/chromaprint/Makefile
  cross/chromaprint/PLIST
  cross/chromaprint/digests
  cross/chromaprint/patches/001-disable-HAVE_AV_FRAME.patch
  cross/docker-tvheadend/Makefile
  cross/docker-tvheadend/digests
  cross/ffmpeg/Makefile
  cross/frei0r/Makefile
  cross/frei0r/PLIST
  cross/frei0r/digests
  cross/libdc1394/Makefile
  cross/libdc1394/PLIST
  cross/libdc1394/digests
  cross/librabbitmq/Makefile
  cross/librabbitmq/PLIST
  cross/librabbitmq/digests
  cross/libzimg/Makefile
  cross/libzimg/PLIST
  cross/libzimg/digests
  mk/spksrc.strip.mk
  spk/chromaprint/Makefile
  spk/ffmpeg/Makefile
  spk/ffmpeg/TODO
Labels: framework

#5297 Fix KVER to omit extra-version and fix UDEV rule check
  spk/synocli-kernel/Makefile
  spk/synocli-kernel/src/synocli-kernelmodule.sh
Labels: bug
