Repository SynoCommunity/spksrc, pull requests merged in 2022-04, with the labels that each got.

#5180 Refactor crossenv spksrc.wheel.mk and build libtorrent
  mk/spksrc.wheel.mk
  spk/python310/Makefile
  spk/python310/src/requirements-crossenv.txt
  spk/python310/src/requirements-pure.txt
Labels: status/needs-review

#5163 spksrc: Fully use DSM7 var directory
  mk/spksrc.configure.mk
  mk/spksrc.copy.mk
  mk/spksrc.cross-cmake-env.mk
  mk/spksrc.directories.mk
  mk/spksrc.install.mk
  mk/spksrc.spk.mk
Labels: framework, status/ready-to-merge

#4976 dotnet: add dotnet 6.0 runtime
  cross/dotnet-runtime/Makefile
  cross/dotnet-runtime/PLIST.auto
  cross/dotnet-runtime/digests
  mk/spksrc.generate-digests.mk
  mk/spksrc.plist.mk
  spk/dotnet-runtime/Makefile
  spk/dotnet-runtime/PLIST
  spk/dotnet-runtime/src/dotnet.png
Labels: dotnet

#5209 Framework cleanup
  cross/bat/Makefile
  cross/dnscrypt-proxy/Makefile
  cross/exa/Makefile
  cross/ffmpeg/Makefile
  cross/fritzctl/Makefile
  cross/fzf/Makefile
  cross/jackett/Makefile
  cross/lame/Makefile
  cross/libnuma/Makefile
  cross/libnuma/PLIST
  cross/libvpx/Makefile
  cross/mariadb-connector-c/Makefile
  cross/micro/Makefile
  cross/mono/Makefile
  cross/mono_58/Makefile
  cross/protobuf/Makefile
  cross/saltgui/Makefile
  cross/sickchill/Makefile
  cross/sickchill/digests
  cross/syncthing/Makefile
  cross/x264/Makefile
  cross/x265/Makefile
  cross/zlib-ng/Makefile
  mk/spksrc.cross-cc.mk
  mk/spksrc.cross-cmake.mk
  mk/spksrc.icon.mk
  mk/spksrc.kernel-flags.mk
  mk/spksrc.patch.mk
  mk/spksrc.service.mk
  mk/spksrc.spk.mk
  mk/spksrc.wheel.mk
Labels: framework

#5214 copy.mk: Fix staging path for var & target/var
  mk/spksrc.copy.mk
Labels: bug

#5223 redesign DSM version requirements
  cross/mkvtoolnix/Makefile
  cross/mono/Makefile
  cross/mono_58/Makefile
  cross/nodejs_v16/Makefile
  mk/spksrc.pre-check.mk
  native/mono/Makefile
  spk/curaengine/Makefile
  spk/darkstat/Makefile
  spk/deluge/Makefile
  spk/he853/Makefile
  spk/lidarr/Makefile
  spk/mkvtoolnix/Makefile
  spk/mono/Makefile
  spk/mono_58/Makefile
  spk/mtproxy/Makefile
  spk/nodejs_v16/Makefile
  spk/owncloud/Makefile
  spk/python310/Makefile
  spk/radarr/Makefile
  spk/tt-rss/Makefile
Labels: framework

#5228 Fix package creation for DSM < 6
  mk/spksrc.service.mk
  mk/spksrc.spk.mk
Labels: framework

#5227 ffmpeg: Disable jellyfin patch causing TVH segfault on DSM7-x64
  cross/ffmpeg/patches/1031-jellyfin-0032-add-async-support-for-qsv-vpp.patch-DISABLED
  spk/ffmpeg/Makefile
Labels: bug
