Repository SynoCommunity/spksrc, pull requests merged in 2022-03, with the labels that each got.

#5048 Borgbackup v1.2.0 update
  cross/borgbackup/Makefile
  cross/borgbackup/PLIST
  cross/borgbackup/digests
  cross/borgbackup/patches/001-remove-useless-endianness-logic.patch
  cross/jpcre2/Makefile
  cross/libb2/Makefile
  cross/libb2/PLIST
  cross/libb2/digests
  cross/rnm/Makefile
  cross/zstd/Makefile
  cross/zstd/PLIST
  cross/zstd/digests
  spk/borgbackup/Makefile
  spk/borgbackup/src/requirements-crossenv.txt
  spk/borgbackup/src/requirements-pure.txt
Labels: status/needs-review

#5155 homeassistant: Issue with numpy on armv5 no longer exists
  spk/homeassistant/Makefile
Labels: status/ready-to-merge

#5157 spksrc: Allow downloading without extracting the toolchain
  .github/actions/download.sh
  mk/spksrc.cross-env.mk
  mk/spksrc.tc.mk
Labels: framework, status/ready-to-merge

#5156 Fix make exit status
  .github/actions/build.sh
  mk/spksrc.cross-cc.mk
  mk/spksrc.cross-dotnet.mk
  mk/spksrc.cross-go.mk
  mk/spksrc.cross-rust.mk
  mk/spksrc.install-resources.mk
  mk/spksrc.spk.mk
Labels: framework, status/needs-review

#5159 download.mk: Allow multiple retries and echo real cmd line
  mk/spksrc.download.mk
Labels: framework, status/ready-to-merge

#5158 Update Maintainer in package INFO file
  Makefile
  mk/spksrc.spk.mk
  spk/bicbucstriim/Makefile
  spk/cops/Makefile
  spk/couchpotatoserver-custom/Makefile
  spk/couchpotatoserver/Makefile
  spk/dante-sockd/Makefile
  spk/darkstat/Makefile
  spk/debian-chroot/Makefile
  spk/deluge/Makefile
  spk/fengoffice/Makefile
  spk/fish/Makefile
  spk/full-text-rss/Makefile
  spk/gateone/Makefile
  spk/haproxy/Makefile
  spk/he853/Makefile
  spk/headphones-custom/Makefile
  spk/headphones/Makefile
  spk/horde/Makefile
  spk/htpcmanager/Makefile
  spk/icecast/Makefile
  spk/itools/Makefile
  spk/jappix/Makefile
  spk/lazylibrarian/Makefile
  spk/lirc/Makefile
  spk/mantisbt/Makefile
  spk/maraschino/Makefile
  spk/memcached/Makefile
  spk/mosquitto/Makefile
  spk/mtproxy/Makefile
  spk/mylar/Makefile
  spk/node-exporter/Makefile
  spk/ntopng/Makefile
  spk/nzbhydra/Makefile
  spk/nzbmegasearch/Makefile
  spk/owncloud/Makefile
  spk/plexivity/Makefile
  spk/plexpy-custom/Makefile
  spk/pyload/Makefile
  spk/python3/Makefile
  spk/roundcube/Makefile
  spk/saltpad/Makefile
  spk/selfoss/Makefile
  spk/shairport-sync/Makefile
  spk/sickbeard-custom/Makefile
  spk/sickrage/Makefile
  spk/sonarr/Makefile
  spk/squidguard/Makefile
  spk/stockfish/Makefile
  spk/subliminal/Makefile
  spk/tcl/Makefile
  spk/transmission/Makefile
  spk/tt-rss/Makefile
  spk/tvheadend/Makefile
  spk/vim/Makefile
  spk/wallabag/Makefile
  spk/zsh/Makefile
Labels: framework

#5162 spk.mk: Fix all-supported and other parallel-build calls
  mk/spksrc.cross-cc.mk
  mk/spksrc.spk.mk
Labels: status/needs-review

#5171 Python 3.10.4 Update
  cross/c-ares/Makefile
  cross/c-ares/PLIST
  cross/c-ares/digests
  cross/curl/Makefile
  cross/curl/digests
  cross/libxml2/Makefile
  cross/libxml2/PLIST
  cross/libxml2/digests
  cross/mariadb-connector-c/Makefile
  cross/mariadb-connector-c/digests
  cross/pip/Makefile
  cross/pip/digests
  cross/python310/Makefile
  cross/python310/digests
  native/python310/Makefile
  native/python310/digests
  spk/python310/Makefile
  spk/python310/src/requirements-crossenv.txt
  spk/python310/src/requirements-pure.txt
Labels: status/work-in-progress
