Repository SynoCommunity/spksrc, pull requests merged in 2022-01, with the labels that each got.

#5023 Wheel building: provide additional arguments
  cross/python310/Makefile
  mk/spksrc.common.mk
  mk/spksrc.wheel.mk
  spk/homeassistant/Makefile
  spk/homeassistant/src/requirements-crossenv.txt
  spk/python310/Makefile
  spk/python310/src/requirements-abi3.txt
  spk/python310/src/requirements-crossenv.txt
  spk/python310/src/requirements-pure.txt
Labels: status/needs-review

#4946 beets: update to 1.5.0 & Dependencies
  cross/pillow/Makefile
  cross/pillow/digests
  spk/beets/Makefile
  spk/beets/src/requirements-crossenv.txt
  spk/beets/src/requirements-pure.txt
Labels: status/ready-to-merge

#5035 git: update 2.34.1
  cross/curl/Makefile
  cross/curl/digests
  cross/git/Makefile
  cross/git/PLIST
  cross/git/digests
  cross/openssl/Makefile
  cross/openssl/digests
  spk/git/Makefile
Labels: status/ready-to-merge

#5028 Add Gitea and update Node.js
  cross/gitea/Makefile
  cross/gitea/PLIST
  cross/gitea/digests
  native/nodejs/Makefile
  native/nodejs/digests
  spk/git-server/Makefile
  spk/git-server/src/app/config
  spk/git-server/src/conf/privilege
  spk/git-server/src/dsm-control.sh
  spk/git-server/src/git-server.png
  spk/git-server/src/gitweb.conf
  spk/git-server/src/gitweb_config.perl
  spk/git-server/src/installer.sh
  spk/git-server/src/wizard/install_uifile
  spk/gitea/Makefile
  spk/gitea/PLIST
  spk/gitea/src/gitea.png
  spk/gitea/src/service-setup.sh
  spk/gitea/src/wizard/install_uifile
Labels: status/ready-to-merge

#4998 Migrate remaining python3 packages to python310
  cross/bazarr/Makefile
  cross/bazarr/digests
  cross/gevent-websocket/Makefile
  cross/gevent-websocket/PLIST
  cross/gevent-websocket/digests
  mk/spksrc.wheel-env.mk
  spk/bazarr/Makefile
  spk/bazarr/src/requirements-crossenv.txt
  spk/bazarr/src/requirements-pure.txt
  spk/bazarr/src/requirements.txt
  spk/bazarr/src/service-setup.sh
  spk/fishnet/Makefile
  spk/fishnet/src/requirements-pure.txt
  spk/fishnet/src/service-setup.sh
  spk/plexpy-custom/Makefile
  spk/plexpy-custom/src/service-setup.sh
  spk/python310/src/requirements-crossenv.txt
  spk/rutorrent/Makefile
  spk/rutorrent/PLIST
  spk/rutorrent/src/requirements-pure.txt
  spk/rutorrent/src/service-setup.sh
Labels: status/ready-to-merge

#5045 mercurial: Update to version 6.0
  cross/mercurial/Makefile
  cross/mercurial/PLIST
  cross/mercurial/digests
  spk/mercurial/Makefile
  spk/mercurial/src/requirements-crossenv.txt
  spk/mercurial/src/requirements-pure.txt
  spk/mercurial/src/requirements.txt
Labels: status/ready-to-merge

#5044 python310: Update to version 3.10.1
  cross/python310/Makefile
  cross/python310/digests
  native/python310/Makefile
  native/python310/digests
  spk/python310/Makefile
  spk/python310/src/requirements-pure.txt
Labels: status/ready-to-merge

#5053 libjpeg: Update from version 9d to 9e and change URL source
  cross/libjpeg/Makefile
  cross/libjpeg/PLIST
  cross/libjpeg/digests
Labels: status/ready-to-merge

#5046 copy.mk: Revert change as it does not handle * PLIST entries
  mk/spksrc.copy.mk
  mk/spksrc.install.mk
  mk/spksrc.plist.mk
Labels: bug

#5050 gdbm: Update from version 1.19 to 1.22
  cross/gdbm/Makefile
  cross/gdbm/digests
Labels: status/ready-to-merge

#5021 New Issue templates
  .github/ISSUE_TEMPLATE.md
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/package-request.md
  .github/ISSUE_TEMPLATE/package-request.yml
  .github/PULL_REQUEST_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE/framework.md
Labels: framework, status/ready-to-merge

#5061 adjust INFO file to exclude archs that are not supported
  mk/spksrc.spk.mk
Labels: framework

#5047 ncurses: Update from version 6.1 to 6.3
  cross/bash/Makefile
  cross/ejabberd/Makefile
  cross/erlang/Makefile
  cross/erlang/patches/000-configure-add-ncursesw-to-termcap-libraries.patch
  cross/irssi/Makefile
  cross/irssi/PLIST
  cross/mg/Makefile
  cross/mg/patches/001-enable-link-with-ncursesw-configure.ac.patch
  cross/mosh/Makefile
  cross/mtr/Makefile
  cross/ncurses/Makefile
  cross/ncurses/PLIST
  cross/ncurses/digests
  cross/ncursesw/Makefile
  cross/ncursesw/PLIST
  cross/ncursesw/digests
  cross/pinentry/Makefile
  cross/plowshare/Makefile
  cross/procps-ng/Makefile
  cross/procps-ng/PLIST
  cross/procps-ng/digests
  cross/rutorrent/Makefile
  cross/tmux/Makefile
  cross/vim/Makefile
  spk/plowshare/Makefile
  spk/plowshare/src/dsm-control.sh
  spk/plowshare/src/installer.sh
  spk/rutorrent/Makefile
Labels: status/ready-to-merge

#5054 duplicity: Update from version 0.8.19 to 0.8.21
  cross/duplicity/Makefile
  cross/duplicity/PLIST
  cross/duplicity/digests
  spk/duplicity/Makefile
  spk/duplicity/src/requirements-crossenv.txt
  spk/duplicity/src/requirements-pure.txt
  spk/duplicity/src/service-setup.sh
Labels: status/to-publish

#5096 homeassistant: Migrate to ujson & numpy using pip
  cross/numpy/Makefile
  cross/numpy/PLIST
  cross/numpy/digests
  cross/numpy/patches/ppc853x/001-remove-error-pragma_not_allowed_inside_functions.patch
  cross/python310/Makefile
  cross/ujson/Makefile
  cross/ujson/PLIST
  cross/ujson/digests
  mk/spksrc.wheel.mk
  spk/bazarr/Makefile
  spk/homeassistant/Makefile
  spk/homeassistant/src/requirements-crossenv.txt
  spk/python310/Makefile
  spk/python310/src/requirements-crossenv.txt
Labels: status/needs-review
