Repository SynoCommunity/spksrc, pull requests merged in 2022-09, with the labels that each got.

#5417 Avoid default value for TCVERSION (followup to #5390)
  mk/spksrc.spk.mk
Labels: framework

#5422 deluge: Fix Tracker Status Error certificate verify failed
  spk/deluge/Makefile
  spk/deluge/src/service-setup.sh
Labels: bug

#5384 ombi: initial package release
  cross/ombi/Makefile
  cross/ombi/PLIST
  cross/ombi/digests
  spk/ombi/Makefile
  spk/ombi/src/ombi.png
  spk/ombi/src/service-setup.sh
Labels: dotnet
