Repository SynoCommunity/spksrc, pull requests merged in 2023-04, with the labels that each got.

#5680 Framework: Update dotnet 6.0 exclusions
  mk/spksrc.archs.mk
Labels: framework, dotnet

#5524 Sonarr v4 beta
  cross/sonarr/Makefile
  cross/sonarr/PLIST
  cross/sonarr/digests
  mk/spksrc.spk.mk
  spk/sonarr/Makefile
  spk/sonarr/src/config.xml
  spk/sonarr/src/service-setup.sh
  spk/sonarr/src/sonarr.png
  spk/sonarr/src/wizard/install_uifile.sh
  spk/sonarr/src/wizard/install_uifile_fre.sh
  spk/sonarr/src/wizard/upgrade_uifile
  spk/sonarr/src/wizard/upgrade_uifile_fre
Labels: status/needs-review

#5110 [New Package] Readarr
  cross/readarr/Makefile
  cross/readarr/PLIST
  cross/readarr/digests
  spk/readarr/Makefile
  spk/readarr/src/config.xml
  spk/readarr/src/readarr.png
  spk/readarr/src/service-setup.sh
  spk/readarr/src/wizard/install_uifile
  spk/readarr/src/wizard/install_uifile_fre
  spk/readarr/src/wizard/upgrade_uifile
  spk/readarr/src/wizard/upgrade_uifile_fre
Labels: status/needs-review, new-package

#5584 Lidarr: Update dotnet build for DSM 7.2
  cross/lidarr-mono/Makefile
  cross/lidarr-mono/PLIST
  cross/lidarr-mono/digests
  cross/lidarr/Makefile
  cross/lidarr/digests
  spk/lidarr/Makefile
  spk/lidarr/src/config.xml
  spk/lidarr/src/service-setup-mono.sh
  spk/lidarr/src/service-setup.sh
  spk/lidarr/src/wizard/install_uifile
  spk/lidarr/src/wizard/install_uifile_fre
  spk/lidarr/src/wizard/upgrade_uifile
  spk/lidarr/src/wizard/upgrade_uifile_fre
Labels: status/needs-review, dotnet, dsm 7.2

#5695 Transmission: Update to 4.0.3
  cross/transmission/Makefile
  cross/transmission/digests
  spk/transmission/Makefile
Labels: status/needs-review

#5707 Lidarr: Fix dotnet dependencies for DSM 7.x
  spk/lidarr/Makefile
  spk/lidarr/src/service-setup.sh
Labels: status/needs-review, dotnet, dsm 7.2

#5701 Framework: Add publish validation check
  .gitignore
  mk/spksrc.spk.mk
Labels: framework, status/ready-to-merge

#5693 Jackett: Update dotnet build for DSM 7.2
  cross/jackett-mono/Makefile
  cross/jackett-mono/digests
  cross/jackett/Makefile
  cross/jackett/digests
  spk/jackett/Makefile
  spk/jackett/src/service-setup.sh
Labels: status/needs-review, dotnet, dsm 7.2

#5713 Framework: Amend publish validation check
  mk/spksrc.spk.mk
Labels: framework

#5706 Jellyfin: Update to v10.8.10
  cross/jellyfin-web/Makefile
  cross/jellyfin-web/digests
  cross/jellyfin/Makefile
  cross/jellyfin/digests
  native/dotnet-sdk-6.0/Makefile
  native/dotnet-sdk-6.0/digests
  spk/jellyfin/Makefile
  spk/jellyfin/src/service-setup.sh
Labels: status/needs-review, dotnet, dsm 7.2

#5696 Sonarr v4: Update dotnet build for DSM 7.2
  cross/sonarr/Makefile
  cross/sonarr/digests
  spk/sonarr/Makefile
  spk/sonarr/src/service-setup.sh
Labels: status/needs-review, dotnet, dsm 7.2

#5697 Radarr: Update dotnet build for DSM 7.2
  cross/radarr/Makefile
  cross/radarr/digests
  spk/radarr/Makefile
  spk/radarr/src/service-setup.sh
Labels: status/needs-review, dotnet, dsm 7.2

#5709 Prowlarr: Update dotnet build for DSM 7.2
  cross/prowlarr/Makefile
  cross/prowlarr/digests
  spk/prowlarr/Makefile
  spk/prowlarr/src/service-setup.sh
Labels: status/needs-review, dotnet, dsm 7.2
