Repository SynoCommunity/spksrc, pull requests merged in 2023-02, with the labels that each got.

#5585 update jellyfin 10.8.9 and dotnet to 6.0.405
  cross/jellyfin-web/Makefile
  cross/jellyfin-web/digests
  cross/jellyfin/Makefile
  cross/jellyfin/digests
  native/dotnet-sdk-6.0/Makefile
  native/dotnet-sdk-6.0/digests
  spk/jellyfin/Makefile
Labels: status/ready-to-merge

#5529 Radarr: fix package update and version bump
  cross/radarr/Makefile
  cross/radarr/digests
  spk/radarr/Makefile
  spk/radarr/src/config.xml
  spk/radarr/src/service-setup.sh
Labels: status/needs-review

#5598 fix github build of go packages
  .github/actions/build.sh
  cross/cloudflared/patches/001-disable-buildvcs.patch
  cross/gdu/patches/000-makefile-set-version-and-build-user-and-force-cgo.patch
  cross/gitea/Makefile
  cross/syncthing/Makefile
  cross/syncthing/patches/001-disable-buildvcs.patch
  mk/spksrc.cross-go-env.mk
Labels: framework

#5602 Framework: fix installer, add arch vars
  mk/spksrc.archs.mk
  mk/spksrc.service.installer.dsm5
  mk/spksrc.service.installer.dsm6
  mk/spksrc.service.installer.dsm7
  mk/spksrc.service.installer.functions
Labels: framework, status/needs-review, dotnet

#5592 Radarr: fix for service setup
  cross/radarr/Makefile
  spk/radarr/Makefile
  spk/radarr/src/service-setup.sh
Labels: framework, status/needs-review

#5601 Sonarr v3: fix for service setup
  spk/sonarr3/Makefile
  spk/sonarr3/src/service-setup.sh
Labels: status/work-in-progress

#5608 Framework: fix for wizard file permissions
  mk/spksrc.spk.mk
Labels: framework

#5600 Misc updates (fribidi, glib, glibmm, pango, libsigc++)
  cross/fribidi/Makefile
  cross/glib-2.66/Makefile
  cross/glib-2.66/PLIST
  cross/glib-2.66/digests
  cross/glib-2.66/patches/hi3535/001-fix-build-SYS_sched_getattr.patch
  cross/glib-latest/Makefile
  cross/glib-latest/PLIST
  cross/glib-latest/digests
  cross/glib-latest/patches/hi3535/001-fix-build-SYS_sched_getattr.patch
  cross/glib/Makefile
  cross/glib/PLIST
  cross/glib/patches/0002-allow-explicit-disabling-of-tests.patch
  cross/glibmm-2.66/Makefile
  cross/glibmm-2.66/PLIST
  cross/glibmm-2.66/digests
  cross/glibmm-latest/Makefile
  cross/glibmm-latest/PLIST
  cross/glibmm-latest/digests
  cross/glibmm/Makefile
  cross/glibmm/PLIST
  cross/glibmm/digests
  cross/json-glib/Makefile
  cross/libsigc++-2.12/Makefile
  cross/libsigc++-2.12/PLIST
  cross/libsigc++-2.12/digests
  cross/libsigc++-latest/Makefile
  cross/libsigc++-latest/PLIST
  cross/libsigc++-latest/digests
  cross/libsigc++/Makefile
  cross/libsigc++/PLIST
  cross/libsigc++/digests
  cross/pango/Makefile
  cross/pango/PLIST
  cross/pango/digests
  mk/spksrc.cross-env.mk
Labels: framework, status/needs-review

#5587 Prowlarr: fix dotnet archs and version bump
  cross/prowlarr/Makefile
  cross/prowlarr/digests
  spk/prowlarr/Makefile
  spk/prowlarr/src/config.xml
  spk/prowlarr/src/service-setup.sh
Labels: status/needs-review

#5604 Mono: fix DSM 7 compatibility
  cross/mono/Makefile
  native/mono/patches/001-relocate-specialfolders.patch
  native/mono_58/patches/001-relocate-specialfolders.patch
  spk/mono/Makefile
Labels: status/needs-review

#5613 Sabnzbd: Fix service setup script
  spk/sabnzbd/src/service-setup.sh
Labels: status/needs-review

#5611 update fontconfig
  cross/fontconfig/Makefile
  cross/fontconfig/PLIST
  cross/fontconfig/digests
  cross/freetype/Makefile
  cross/freetype/PLIST
  cross/freetype/digests
Labels: status/ready-to-merge

#5615 Mosh: Update to v1.4.0
  cross/mosh/Makefile
  cross/mosh/digests
  spk/mosh/Makefile
Labels: status/needs-review

#5455 rutorrent: DSM7 support + fix torrent creation wizard
  spk/rutorrent/Makefile
  spk/rutorrent/src/bin/rtorrent-daemon
  spk/rutorrent/src/conf/resource
  spk/rutorrent/src/rtorrent.rc
  spk/rutorrent/src/service-setup.sh
  spk/rutorrent/src/wizard/install_uifile
  spk/rutorrent/src/wizard/install_uifile_fre
  spk/rutorrent/src/wizard/upgrade_uifile
  spk/rutorrent/src/wizard_templates/install_uifile.sh
  spk/rutorrent/src/wizard_templates/shared_uifile_setup.sh
  spk/rutorrent/src/wizard_templates/uifile_vars
  spk/rutorrent/src/wizard_templates/uifile_vars_fre
  spk/rutorrent/src/wizard_templates/upgrade_uifile.sh
Labels: status/needs-review

#5596 Dotnet runtime: Update to v6.0.14
  cross/dotnet-runtime/Makefile
  cross/dotnet-runtime/digests
  spk/dotnet-runtime/Makefile
Labels: status/needs-review, dotnet
