Repository SynoCommunity/spksrc, pull requests merged in 2023-05, with the labels that each got.

#5724 Update to python 3.8.16, 3.10.11 and 3.11.3
  cross/cryptography/Makefile
  cross/cryptography/digests
  cross/mariadb-connector-c/Makefile
  cross/mariadb-connector-c/PLIST
  cross/mariadb-connector-c/digests
  cross/pip/Makefile
  cross/pip/digests
  cross/python310/Makefile
  cross/python310/digests
  cross/python311/Makefile
  cross/python311/digests
  cross/python38/Makefile
  cross/python38/digests
  mk/spksrc.cross-cmake.mk
  native/python310/Makefile
  native/python310/digests
  native/python311/Makefile
  native/python311/digests
  native/python38/Makefile
  native/python38/digests
  spk/octoprint/src/requirements-crossenv.txt
  spk/python310/Makefile
  spk/python310/src/requirements-crossenv-numpy.txt
  spk/python310/src/requirements-crossenv.txt
  spk/python310/src/requirements-pure.txt
  spk/python311/Makefile
  spk/python311/src/requirements-crossenv-numpy-armv7l.txt
  spk/python311/src/requirements-crossenv-numpy.txt
  spk/python311/src/requirements-crossenv.txt
  spk/python311/src/requirements-pure.txt
  spk/python38/Makefile
Labels: status/needs-review

#5654 bazarr: update 1.1.4 => 1.2.1
  cross/bazarr/Makefile
  cross/bazarr/digests
  spk/bazarr/Makefile
  spk/bazarr/src/requirements-crossenv.txt
Labels: status/needs-review

#5708 Readarr: Fix dotnet dependencies for DSM 7.x
  spk/readarr/Makefile
  spk/readarr/src/service-setup.sh
Labels: status/needs-review, dotnet, dsm 7.2

#5741 Ombi: Update to v4.39.1
  cross/ombi/Makefile
  cross/ombi/digests
  spk/ombi/Makefile
Labels: dotnet

#5617 rutorrent: upgrade 3.10 => 4.1.5
  cross/rutorrent/Makefile
  cross/rutorrent/digests
  cross/rutorrent/patches/002-fixing-default-value-for-local-hosted-mode.patch
  spk/rutorrent/Makefile
  spk/rutorrent/src/requirements-pure.txt
  spk/rutorrent/src/service-setup.sh
Labels: status/needs-review
