Repository SynoCommunity/spksrc, pull requests merged in 2023-03, with the labels that each got.

#5655 update meson build
  mk/spksrc.cross-meson.mk
Labels: framework, build/meson

#5623 avoid dotnet packages for SRM
  mk/spksrc.archs.mk
Labels: srm

#5597 Jackett: Update to v0.20.3521
  cross/jackett-mono/Makefile
  cross/jackett-mono/digests
  cross/jackett/Makefile
  cross/jackett/digests
  spk/jackett/Makefile
Labels: status/needs-review

#5616 Transmission: Update to v4.0.2
  cross/transmission/Makefile
  cross/transmission/digests
  cross/transmission/patches/001-no-debug.patch
  spk/transmission/Makefile
  spk/transmission/src/service-setup.sh
  spk/transmission/src/wizard/7.0/install_uifile
  spk/transmission/src/wizard/7.0/upgrade_uifile
  spk/transmission/src/wizard/install_uifile
  spk/transmission/src/wizard/install_uifile.sh
  spk/transmission/src/wizard/upgrade_uifile
Labels: status/needs-review

#5619 ownCloud: Update to version 10.12
  cross/owncloud/Makefile
  cross/owncloud/digests
  mk/spksrc.icon.mk
  spk/owncloud/Makefile
  spk/owncloud/src/app/config
  spk/owncloud/src/autoconfig.php
  spk/owncloud/src/bin/owncloud-daemon
  spk/owncloud/src/conf/PKG_DEPS
  spk/owncloud/src/conf/resource
  spk/owncloud/src/dsm-control.sh
  spk/owncloud/src/installer.sh
  spk/owncloud/src/owncloud.png
  spk/owncloud/src/owncloud.sh
  spk/owncloud/src/service-setup.sh
  spk/owncloud/src/web/owncloud.conf
  spk/owncloud/src/web/owncloud.json
  spk/owncloud/src/wizard/install_uifile
  spk/owncloud/src/wizard/install_uifile.sh
  spk/owncloud/src/wizard/install_uifile_fre
  spk/owncloud/src/wizard/install_uifile_fre.sh
  spk/owncloud/src/wizard/uninstall_uifile
  spk/owncloud/src/wizard/uninstall_uifile.sh
  spk/owncloud/src/wizard/uninstall_uifile_fre
  spk/owncloud/src/wizard/uninstall_uifile_fre.sh
  spk/owncloud/src/wizard/upgrade_uifile.sh
  spk/owncloud/src/wizard/upgrade_uifile_fre.sh
Labels: status/needs-review
