Repository SynoCommunity/spksrc, pull requests merged in 2023-09, with the labels that each got.

#5863 Transmission: Update to 4.0.4
  cross/transmission/Makefile
  cross/transmission/digests
  spk/transmission/Makefile
Labels: status/needs-review

#5864 Ombi: Update to v4.43.5
  cross/ombi/Makefile
  cross/ombi/digests
  spk/ombi/Makefile
  spk/ombi/src/ombi.png
Labels: status/needs-review

#5868 SynoCli Disk Tools: Add support for r1000 arch
  spk/synocli-disk/Makefile
Labels: arch

#5873 Disable supported archs checks for dependency evaluation
  .github/actions/prepare.sh
  mk/spksrc.pre-check.mk
Labels: framework

#5874 Attempt at fixing publishing whith dependent packages
  .github/actions/build.sh
  .github/actions/prepare.sh
Labels: status/needs-review

#5876 Attempt no. 2 at fixing publishing whith dependent packages
  .github/actions/build.sh
  .github/workflows/build.yml
Labels: status/needs-review

#5898 synocli-disk: update tools
  .github/actions/prepare.sh
  cross/davfs2/Makefile
  cross/davfs2/digests
  cross/ddrescue/Makefile
  cross/ddrescue/digests
  cross/ddrescue/patches/001-remove-default-env-flags.patch
  cross/dua/Makefile
  cross/dua/digests
  cross/e2fsprogs/Makefile
  cross/e2fsprogs/digests
  cross/gdu/Makefile
  cross/gdu/digests
  cross/gdu/patches/000-makefile-set-version-and-build-user-and-force-cgo.patch
  cross/libthreadar/Makefile
  cross/libthreadar/PLIST
  cross/libthreadar/digests
  cross/lsscsi/Makefile
  cross/lzo/Makefile
  cross/ntfs-3g_ntfsprogs/Makefile
  cross/ntfs-3g_ntfsprogs/digests
  diyspk/dar/Makefile
  diyspk/davfs2/Makefile
  diyspk/diskutils/Makefile
  diyspk/dua/Makefile
  diyspk/gdu/Makefile
  spk/synocli-disk/Makefile
Labels: framework

#5902 Jellyfin: Update to v10.8.11
  cross/jellyfin-web/Makefile
  cross/jellyfin-web/digests
  cross/jellyfin/Makefile
  cross/jellyfin/digests
  native/dotnet-sdk-6.0/Makefile
  native/dotnet-sdk-6.0/digests
  spk/jellyfin/Makefile
Labels: dotnet

#5905 Update SABnzbd to 4.1.0, update UnRar to 6.23 and add par2cmdline-turbo
  cross/par2cmdline-turbo/Makefile
  cross/par2cmdline-turbo/PLIST
  cross/par2cmdline-turbo/digests
  cross/par2cmdline/Makefile
  cross/par2cmdline/digests
  cross/par2cmdline/patches/88f6281/c++11-to-c++0x.patch
  cross/sabnzbd/Makefile
  cross/sabnzbd/digests
  cross/unrar/Makefile
  cross/unrar/digests
  spk/sabnzbd/Makefile
  spk/sabnzbd/src/requirements-crossenv.txt
  spk/sabnzbd/src/requirements-pure.txt
Labels: status/needs-review
