Repository SynoCommunity/spksrc, pull requests merged in 2024-06, with the labels that each got.

#6132 ownCloud: Update to v10.14.0
  cross/owncloud/Makefile
  cross/owncloud/digests
  spk/owncloud/Makefile
  spk/owncloud/src/conf/resource
  spk/owncloud/src/web/owncloud.json
Labels: status/ready-to-merge

#6133 fix qoriq rust with github build
  .github/workflows/build.yml
Labels: framework

#5845 add kopia
  .github/actions/download.sh
  cross/kopia/Makefile
  cross/kopia/PLIST
  cross/kopia/digests
  mk/spksrc.download.mk
  spk/kopia/Makefile
  spk/kopia/src/kopia.png
  spk/kopia/src/service-setup.sh
  spk/kopia/src/wizard/install_uifile
Labels: new-package

#6126 Transmission: Update to 4.0.6
  cross/transmission/Makefile
  cross/transmission/digests
  spk/transmission/Makefile
Labels: status/ready-to-merge

#6131 Kavita: Update to v0.8.1
  cross/kavita/Makefile
  cross/kavita/digests
  spk/kavita/Makefile
Labels: status/ready-to-merge

#6163 fix initialization of SHARE_PATH variable on DSM 7
  mk/spksrc.service.installer.functions
Labels: framework
