Repository SynoCommunity/spksrc, pull requests merged in 2024-11, with the labels that each got.

#6293 Jellyfin: Update to v10.10.0
  cross/jellyfin-web/Makefile
  cross/jellyfin-web/digests
  cross/jellyfin/Makefile
  cross/jellyfin/digests
  native/dotnet-sdk-8.0/Makefile
  native/dotnet-sdk-8.0/digests
  native/nodejs/Makefile
  native/nodejs/digests
  spk/jellyfin/Makefile
Labels: status/ready-to-merge, dotnet

#6302 Jellyfin: Update to v10.10.1
  cross/jellyfin-web/Makefile
  cross/jellyfin-web/digests
  cross/jellyfin/Makefile
  cross/jellyfin/digests
  spk/jellyfin/Makefile
Labels: dotnet

#6311 toolchains: fix TC_GLIBC
  toolchain/syno-alpine-7.0/Makefile
  toolchain/syno-alpine-7.1/Makefile
  toolchain/syno-alpine4k-7.0/Makefile
  toolchain/syno-alpine4k-7.1/Makefile
Labels: framework

#6164 bazarr: update 1.4.2 => 1.4.5 and migrate to ffmpeg 7
  cross/bazarr/Makefile
  cross/bazarr/digests
  spk/bazarr/Makefile
  spk/bazarr/src/service-setup.sh
Labels: status/needs-review

#6312 local.mk: add option to disable github api call for maintainer
  Makefile
  mk/spksrc.spk.mk
Labels: framework

#5376 navidrome: initial package release
  cross/navidrome/Makefile
  cross/navidrome/PLIST
  cross/navidrome/digests
  cross/navidrome/patches/001-patch_taglib-wrapper-for-older-gcc.patch
  cross/taglib/Makefile
  cross/taglib/PLIST
  cross/taglib/digests
  spk/navidrome/Makefile
  spk/navidrome/src/navidrome.png
  spk/navidrome/src/navidrome.toml
  spk/navidrome/src/service-setup.sh
  spk/navidrome/src/wizard/install_uifile
Labels: new-package

#6320 Jellyfin: Update to v10.10.3
  cross/jellyfin-web/Makefile
  cross/jellyfin-web/digests
  cross/jellyfin/Makefile
  cross/jellyfin/digests
  native/dotnet-sdk-8.0/Makefile
  native/dotnet-sdk-8.0/digests
  spk/jellyfin/Makefile
Labels: dotnet

#6228 ffsync: Update syncstorage-rs to v0.17.15
  cross/diesel/Makefile
  cross/syncstorage-rs/Makefile
  cross/syncstorage-rs/digests
  spk/ffsync/Makefile
Labels: build/rust
