Repository SynoCommunity/spksrc, pull requests merged in 2024-12, with the labels that each got.

#6341 cops, bicbucstriim: Amend build for DSM 7.2
  .github/workflows/build.yml
  cross/bicbucstriim/Makefile
  cross/bicbucstriim/digests
  cross/cops/Makefile
  cross/cops/digests
  spk/bicbucstriim/Makefile
  spk/cops/Makefile
Labels: framework

#6345 dotnet 6 and 8: update dotnet-sdk and dotnet-runtime
  cross/dotnet-runtime/Makefile
  cross/dotnet-runtime/digests
  cross/dotnet8-runtime/Makefile
  cross/dotnet8-runtime/digests
  native/dotnet-sdk-6.0/Makefile
  native/dotnet-sdk-6.0/digests
  spk/dotnet-runtime/Makefile
  spk/dotnet8-runtime/Makefile
Labels: dotnet

#6344 [New package] .NET 9
  cross/dotnet9-runtime/Makefile
  cross/dotnet9-runtime/PLIST.auto
  cross/dotnet9-runtime/digests
  spk/dotnet9-runtime/Makefile
  spk/dotnet9-runtime/src/dotnet.png
Labels: new-package
