Repository SynoCommunity/spksrc, pull requests merged in 2024-10, with the labels that each got.

#6247 Framework: Add Configurable Build Architectures and Input Flags
  .github/workflows/build.yml
Labels: framework, status/needs-review

#5992 Feng Office: Update to v3.11.2.8
  cross/fengoffice/Makefile
  cross/fengoffice/digests
  spk/fengoffice/Makefile
  spk/fengoffice/src/conf/PKG_DEPS
  spk/fengoffice/src/conf/resource
  spk/fengoffice/src/conf_6/privilege
  spk/fengoffice/src/conf_6/resource
  spk/fengoffice/src/dsm-control.sh
  spk/fengoffice/src/fengoffice.sh
  spk/fengoffice/src/installer.sh
  spk/fengoffice/src/service-setup.sh
  spk/fengoffice/src/web/fengoffice.conf
  spk/fengoffice/src/web/fengoffice.json
  spk/fengoffice/src/wizard/install_uifile
  spk/fengoffice/src/wizard/install_uifile.sh
  spk/fengoffice/src/wizard/uninstall_uifile
  spk/fengoffice/src/wizard/uninstall_uifile.sh
  spk/fengoffice/src/wizard/upgrade_uifile
Labels: status/ready-to-merge

#6229 BicBucStriim: Update to v3.4.2
  cross/bicbucstriim/Makefile
  cross/bicbucstriim/digests
  spk/bicbucstriim/Makefile
  spk/bicbucstriim/src/conf/resource
  spk/bicbucstriim/src/service-setup.sh
  spk/bicbucstriim/src/web/bicbucstriim.conf
  spk/bicbucstriim/src/web/bicbucstriim.json
  spk/bicbucstriim/src/wizard/install_uifile.sh
Labels: status/ready-to-merge

#6230 COPS: Update to v3.2.2
  cross/cops/Makefile
  cross/cops/digests
  spk/cops/Makefile
  spk/cops/src/conf/resource
  spk/cops/src/conf_6/resource
  spk/cops/src/service-setup.sh
  spk/cops/src/web/cops.conf
  spk/cops/src/web/cops.json
  spk/cops/src/wizard_templates/install_uifile
  spk/cops/src/wizard_templates/install_uifile.yml
  spk/cops/src/wizard_templates/install_uifile_fre.yml
  spk/cops/src/wizard_templates/upgrade_uifile.sh
Labels: status/ready-to-merge

#6232 Wallabag: Update to v2.6.9
  cross/wallabag/Makefile
  cross/wallabag/digests
  spk/wallabag/Makefile
  spk/wallabag/src/app/config
  spk/wallabag/src/conf/resource
  spk/wallabag/src/conf_6/privilege
  spk/wallabag/src/conf_6/resource
  spk/wallabag/src/service-setup.sh
  spk/wallabag/src/web/index.php
  spk/wallabag/src/web/parameters.yml
  spk/wallabag/src/web/wallabag.conf
  spk/wallabag/src/web/wallabag.json
  spk/wallabag/src/wizard/install_uifile
  spk/wallabag/src/wizard/install_uifile.sh
  spk/wallabag/src/wizard/uninstall_uifile
  spk/wallabag/src/wizard/uninstall_uifile.sh
  spk/wallabag/src/wizard/upgrade_uifile.sh
Labels: status/ready-to-merge

#6237 MantisBT: Update to v2.26.3
  cross/mantisbt/Makefile
  cross/mantisbt/digests
  cross/mantisbt/patches/01-admin-install-check-webservice.patch
  spk/mantisbt/Makefile
  spk/mantisbt/src/conf/PKG_DEPS
  spk/mantisbt/src/conf/resource
  spk/mantisbt/src/conf_6/privilege
  spk/mantisbt/src/conf_6/resource
  spk/mantisbt/src/dsm-control.sh
  spk/mantisbt/src/installer.sh
  spk/mantisbt/src/service-setup.sh
  spk/mantisbt/src/web/config_inc.php
  spk/mantisbt/src/web/mantisbt.conf
  spk/mantisbt/src/web/mantisbt.json
  spk/mantisbt/src/wizard/install_uifile
  spk/mantisbt/src/wizard/install_uifile.sh
  spk/mantisbt/src/wizard/uninstall_uifile
  spk/mantisbt/src/wizard/uninstall_uifile.sh
  spk/mantisbt/src/wizard/upgrade_uifile
Labels: status/ready-to-merge

#6243 Roundcube Webmail: Update to v1.6.9
  cross/roundcube/Makefile
  cross/roundcube/digests
  spk/roundcube/Makefile
  spk/roundcube/src/conf/PKG_DEPS
  spk/roundcube/src/conf/resource
  spk/roundcube/src/conf_6/privilege
  spk/roundcube/src/conf_6/resource
  spk/roundcube/src/dsm-control.sh
  spk/roundcube/src/installer.sh
  spk/roundcube/src/service-setup.sh
  spk/roundcube/src/web/roundcube.conf
  spk/roundcube/src/web/roundcube.json
  spk/roundcube/src/wizard/install_uifile
  spk/roundcube/src/wizard/install_uifile.sh
  spk/roundcube/src/wizard/uninstall_uifile
  spk/roundcube/src/wizard/uninstall_uifile.sh
  spk/roundcube/src/wizard/upgrade_uifile
Labels: status/ready-to-merge

#6252 fix ffmpeg build dependency
  mk/spksrc.ffmpeg.mk
Labels: framework

#6254 Jellyfin: Update v10.9.11 to include .NET v8.0.8
  native/dotnet-sdk-8.0/Makefile
  native/dotnet-sdk-8.0/digests
  spk/jellyfin/Makefile
Labels: dotnet

#6259 COPS: Revision for v3.2.2
  spk/cops/Makefile
  spk/cops/src/wizard_templates/upgrade_uifile.sh
  spk/cops/src/wizard_templates/upgrade_uifile.yml
  spk/cops/src/wizard_templates/upgrade_uifile_fre.yml
Labels: status/work-in-progress

#6251 Wallabag: Update PHP extensions
  spk/wallabag/Makefile
  spk/wallabag/src/conf/resource
  spk/wallabag/src/service-setup.sh
  spk/wallabag/src/web/wallabag.json
Labels: status/ready-to-merge

#6280 ownCloud: Revision for v10.15.0
  spk/owncloud/Makefile
  spk/owncloud/src/conf/resource
  spk/owncloud/src/service-setup.sh
  spk/owncloud/src/web/owncloud.json
  spk/owncloud/src/wizard_templates/install_uifile.sh
  spk/owncloud/src/wizard_templates/install_uifile.yml
  spk/owncloud/src/wizard_templates/install_uifile_fre.yml
Labels: status/ready-to-merge

#6290 BicBucStriim: Update to v3.5.2
  cross/bicbucstriim/Makefile
  cross/bicbucstriim/digests
  spk/bicbucstriim/Makefile
Labels: status/ready-to-merge

#6227 synocli-misc: add ts of moreutils
  cross/moreutils/Makefile
  cross/moreutils/PLIST
  spk/synocli-misc/Makefile
Labels: synocli-misc
