Repository SynoCommunity/spksrc, pull requests merged in 2024-01, with the labels that each got.

#5962 COPS: Enhance Upgrade Process for Legacy Versions
  spk/cops/Makefile
  spk/cops/src/conf/resource
  spk/cops/src/conf_6/resource
  spk/cops/src/service-setup.sh
  spk/cops/src/wizard_templates/upgrade_uifile.sh
  spk/cops/src/wizard_templates/upgrade_uifile.yml
  spk/cops/src/wizard_templates/upgrade_uifile_fre.yml
Labels: status/ready-to-merge

#5968 Update SABnzbd to 4.2.1
  cross/sabnzbd/Makefile
  cross/sabnzbd/digests
  spk/sabnzbd/Makefile
  spk/sabnzbd/src/requirements-crossenv.txt
  spk/sabnzbd/src/requirements-pure.txt
  spk/sabnzbd/src/service-setup.sh
  spk/sabnzbd/src/wizard/install_uifile
  spk/sabnzbd/src/wizard/upgrade_uifile
  spk/sabnzbd/src/wizard/upgrade_uifile.sh
Labels: status/work-in-progress

#5980 Sonarr v4: Update to v4.0.0.748
  cross/sonarr/Makefile
  cross/sonarr/digests
  spk/sonarr/Makefile
  spk/sonarr/src/config.xml
  spk/sonarr/src/service-setup.sh
Labels: status/ready-to-merge

#5983 Readarr: Update to v0.3.14.2358
  cross/readarr/Makefile
  cross/readarr/digests
  mk/spksrc.archs.mk
  spk/readarr/Makefile
Labels: status/work-in-progress

#5978 [New Package] Kavita
  cross/kavita/Makefile
  cross/kavita/PLIST
  cross/kavita/digests
  spk/kavita/Makefile
  spk/kavita/src/appsettings.json
  spk/kavita/src/kavita.png
  spk/kavita/src/service-setup.sh
  spk/kavita/src/wizard/install_uifile
  spk/kavita/src/wizard/install_uifile_fre
Labels: status/ready-to-merge, new-package

#5927 [Framework] Add error detection to python pip calls
  mk/spksrc.service.installer.functions
Labels: framework
