Repository SynoCommunity/spksrc, pull requests merged in 2024-04, with the labels that each got.

#6002 Add generic spksrc.supported.mk
  .gitignore
  Makefile
  cross/libwebp/Makefile
  cross/mysql-connector-c/Makefile
  cross/openjpeg/Makefile
  cross/x265/Makefile
  cross/x265/patches/001-fix-dynamicHDR-flags-arm64.patch
  cross/x265/patches/002-detect512-on-all-archs.patch
  cross/x265/patches/003-fix-version-info-arm64.patch
  cross/zstd/Makefile
  mk/spksrc.archs.mk
  mk/spksrc.common-rules.mk
  mk/spksrc.common.mk
  mk/spksrc.compile.mk
  mk/spksrc.cross-cc.mk
  mk/spksrc.cross-cmake-env.mk
  mk/spksrc.cross-cmake.mk
  mk/spksrc.cross-dotnet.mk
  mk/spksrc.cross-env.mk
  mk/spksrc.cross-go-env.mk
  mk/spksrc.cross-go.mk
  mk/spksrc.cross-kernel-configure.mk
  mk/spksrc.cross-kernel-flags.mk
  mk/spksrc.cross-kernel-headers.mk
  mk/spksrc.cross-kernel-module.mk
  mk/spksrc.cross-kernel.mk
  mk/spksrc.cross-meson-env.mk
  mk/spksrc.cross-meson.mk
  mk/spksrc.cross-ninja.mk
  mk/spksrc.cross-rust-env.mk
  mk/spksrc.cross-rust.mk
  mk/spksrc.dependency-tree.mk
  mk/spksrc.directories.mk
  mk/spksrc.install-resources.mk
  mk/spksrc.kernel-required.mk
  mk/spksrc.kernel.mk
  mk/spksrc.main-depends.mk
  mk/spksrc.native-cc.mk
  mk/spksrc.native-cmake.mk
  mk/spksrc.native-env.mk
  mk/spksrc.native-install.mk
  mk/spksrc.native-meson.mk
  mk/spksrc.plist.mk
  mk/spksrc.publish.mk
  mk/spksrc.python.mk
  mk/spksrc.spk.mk
  mk/spksrc.supported.mk
  mk/spksrc.tc-rust.mk
  mk/spksrc.tc.mk
  mk/spksrc.test-rules.mk
  mk/spksrc.toolkit.mk
  spk/gateone/BROKEN
  toolchain/syno-qoriq-6.2.4/Makefile
Labels: framework, status/needs-review

#5032 synocli Disk: update tools and add s3backer
  cross/argon2/Makefile
  cross/argon2/PLIST
  cross/argon2/digests
  cross/attr/Makefile
  cross/attr/PLIST
  cross/attr/digests
  cross/dar/Makefile
  cross/dar/PLIST
  cross/dar/digests
  cross/dar/patches/001-configure-crosscompile.patch
  cross/dar/patches/001-disable-build-of-src_check.patch
  cross/dar/patches/002-avoid-cross-compiling-error.patch
  cross/ddrescue/Makefile
  cross/ddrescue/digests
  cross/dua/Makefile
  cross/dua/digests
  cross/librsync/Makefile
  cross/librsync/PLIST
  cross/librsync/digests
  cross/libthreadar/patches/001-fix-include-path.patch
  cross/s3backer/Makefile
  cross/s3backer/PLIST
  cross/s3backer/digests
  diyspk/dar/Makefile
  diyspk/ddrescue/Makefile
  diyspk/dua/Makefile
  diyspk/s3backer/Makefile
  spk/synocli-disk/Makefile
Labels: new-cli-tool

#5860 [ariang] Add package
  cross/ariang/Makefile
  cross/ariang/PLIST
  cross/ariang/digests
  spk/ariang/Makefile
  spk/ariang/src/ariang.png
  spk/ariang/src/conf/resource
  spk/ariang/src/dsm-control.sh
Labels: new-package
