Repository SynoCommunity/spksrc, pull requests merged in 2025-01, with the labels that each got.

#6369 Framework: Fix to handle empty matrix
  .github/workflows/build.yml
Labels: framework

#6374 native/nodejs: update to v22 (current LTS version)
  native/nodejs/Makefile
  native/nodejs/digests
Labels: framework

#6318 add SRM 1.3 toolchains
  .github/workflows/build.yml
  mk/spksrc.archs.mk
  mk/spksrc.tc-vers.mk
  toolchain/syno-aarch64-1.3/Makefile
  toolchain/syno-aarch64-1.3/digests
  toolchain/syno-armv7-1.3/Makefile
  toolchain/syno-armv7-1.3/digests
  toolchain/syno-cypress-1.3/Makefile
  toolchain/syno-cypress-1.3/digests
  toolchain/syno-dakota-1.3/Makefile
  toolchain/syno-dakota-1.3/digests
  toolchain/syno-hawkeye-1.3/Makefile
  toolchain/syno-hawkeye-1.3/digests
  toolchain/syno-ipq806x-1.3/Makefile
  toolchain/syno-ipq806x-1.3/digests
Labels: framework, srm

#6401 native/go: update to v1.23.5
  native/go/Makefile
  native/go/digests
Labels: framework

#6389 wheel.mk: Migrate to using status cookie
  .github/actions/download.sh
  mk/spksrc.common.mk
  mk/spksrc.crossenv.mk
  mk/spksrc.python-module.mk
  mk/spksrc.python-wheel.mk
  mk/spksrc.spk.mk
  mk/spksrc.wheel-compile.mk
  mk/spksrc.wheel-download.mk
  mk/spksrc.wheel-env.mk
  mk/spksrc.wheel-install.mk
  mk/spksrc.wheel.mk
Labels: framework

#6255 Redesign dependency-list creation for github prepare action
  .github/actions/prepare.sh
  Makefile
  cross/python2/Makefile
  cross/python38/Makefile
  cross/stockfish-webgui/digests
  cross/vim/Makefile
  diyspk/bandwhich/Makefile
  diyspk/bottom/Makefile
  diyspk/cpulimit/Makefile
  diyspk/duf/Makefile
  diyspk/dutree/Makefile
  diyspk/etherwake/Makefile
  diyspk/fritzctl/Makefile
  diyspk/jupp/Makefile
  diyspk/mtr/Makefile
  diyspk/procs/Makefile
  diyspk/tdu/Makefile
  diyspk/testdisk/Makefile
  mk/dependency-list.sh
  spk/adminer/Makefile
  spk/curaengine/Makefile
  spk/dante-sockd/Makefile
  spk/darkstat/Makefile
  spk/dnscrypt-proxy/Makefile
  spk/gateone/Makefile
  spk/haproxy/Makefile
  spk/he853/Makefile
  spk/icecast/Makefile
  spk/jappix/Makefile
  spk/lirc/Makefile
  spk/mediainfo/Makefile
  spk/monitoring-plugins/Makefile
  spk/mtproxy/Makefile
  spk/node-exporter/Makefile
  spk/pyload/Makefile
  spk/roundcube/Makefile
  spk/shairport-sync/Makefile
  spk/stockfish/Makefile
  spk/stunnel/Makefile
  spk/tt-rss/Makefile
  spk/umurmur/Makefile
  spk/zsh-static/Makefile
Labels: framework

#6372 synocli-file: update tools and remove fd-find for hi3535
  cross/bat/Makefile
  cross/eza/Makefile
  cross/eza/digests
  cross/fd/Makefile
  cross/fd_8.7.0/Makefile
  cross/fd_8.7.0/PLIST
  cross/fd_8.7.0/digests
  cross/fd_9.0.0/Makefile
  cross/fd_9.0.0/PLIST
  cross/fd_9.0.0/digests
  cross/file/Makefile
  cross/file/digests
  cross/fzf/Makefile
  cross/fzf/digests
  cross/nano/Makefile
  cross/nano/digests
  cross/nnn/Makefile
  cross/nnn/digests
  cross/nnn_4.0/Makefile
  cross/nnn_4.8/Makefile
  cross/nnn_4.8/PLIST
  cross/nnn_4.8/digests
  cross/tree/Makefile
  cross/tree/digests
  cross/tree/patches/001-enable-cross-compiler-definitions.patch
  diyspk/eza/Makefile
  diyspk/fd/Makefile
  diyspk/file/Makefile
  diyspk/fzf/Makefile
  diyspk/nano/Makefile
  diyspk/nnn/Makefile
  diyspk/tree/Makefile
  mk/spksrc.cross-rust-env.mk
  spk/synocli-file/Makefile
Labels: synocli-file

#6393 Update dotnet 8 -> 8.0.12 & 9 -> 9.0.1
  cross/dotnet8-runtime/Makefile
  cross/dotnet8-runtime/digests
  cross/dotnet9-runtime/Makefile
  cross/dotnet9-runtime/digests
  native/dotnet-sdk-8.0/Makefile
  native/dotnet-sdk-8.0/digests
  spk/dotnet8-runtime/Makefile
  spk/dotnet9-runtime/Makefile
Labels: dotnet

#6406 ffsync: Update syncstorage-rs to v0.18.2
  cross/syncstorage-rs/Makefile
  cross/syncstorage-rs/digests
  spk/ffsync/Makefile
Labels: build/rust

#6413 Jellyfin: Update to v10.10.4
  cross/jellyfin-web/Makefile
  cross/jellyfin-web/digests
  cross/jellyfin/Makefile
  cross/jellyfin/digests
  spk/jellyfin/Makefile
Labels: dotnet

#6418 fix publish
  mk/spksrc.publish.mk
Labels: framework

#6152 add QEMU Guest Agent
  cross/qemu/Makefile
  cross/qemu/PLIST
  cross/qemu/digests
  spk/qemu-ga/Makefile
  spk/qemu-ga/src/qemu.png
  spk/qemu-ga/src/service-setup.sh
  spk/qemu-ga/src/wizard/install_uifile
  spk/qemu-ga/src/wizard/upgrade_uifile
Labels: new-package
