Repository SynoCommunity/spksrc, pull requests merged in 2025-06, with the labels that each got.

#6519 Build Script: Add strict mode, error trapping, and checksum verification
  .github/actions/download.sh
  mk/spksrc.download.mk
  mk/spksrc.main-depends.mk
Labels: framework, status/ready-to-merge

#6606 Update DSM 7.2 toolchains
  mk/spksrc.tc-vers.mk
  toolchain/syno-aarch64-7.2/digests
  toolchain/syno-alpine-7.2/digests
  toolchain/syno-alpine4k-7.2/digests
  toolchain/syno-apollolake-7.2/Makefile
  toolchain/syno-apollolake-7.2/digests
  toolchain/syno-armada37xx-7.2/digests
  toolchain/syno-armada38x-7.2/digests
  toolchain/syno-armv7-7.2/digests
  toolchain/syno-avoton-7.2/digests
  toolchain/syno-braswell-7.2/digests
  toolchain/syno-broadwell-7.2/Makefile
  toolchain/syno-broadwell-7.2/digests
  toolchain/syno-broadwellnk-7.2/digests
  toolchain/syno-broadwellnkv2-7.2/digests
  toolchain/syno-broadwellntbap-7.2/digests
  toolchain/syno-bromolow-7.2/digests
  toolchain/syno-denverton-7.2/digests
  toolchain/syno-epyc7002-7.2/digests
  toolchain/syno-geminilake-7.2/digests
  toolchain/syno-geminilakenk-7.2/Makefile
  toolchain/syno-geminilakenk-7.2/digests
  toolchain/syno-grantley-7.2/digests
  toolchain/syno-kvmx64-7.2/digests
  toolchain/syno-monaco-7.2/digests
  toolchain/syno-purley-7.2/digests
  toolchain/syno-r1000-7.2/digests
  toolchain/syno-r1000nk-7.2/Makefile
  toolchain/syno-r1000nk-7.2/digests
  toolchain/syno-rtd1296-7.2/digests
  toolchain/syno-rtd1619b-7.2/digests
  toolchain/syno-v1000-7.2/digests
  toolchain/syno-v1000nk-7.2/Makefile
  toolchain/syno-v1000nk-7.2/digests
  toolchain/syno-x64-7.2/Makefile
  toolchain/syno-x64-7.2/digests
Labels: framework, synology, dsm 7.2

#6447 Beets: Update to v2.3.1 and migrate to Python 3.12
  cross/gobject-introspection/Makefile
  cross/gobject-introspection/digests
  cross/mp3gain/Makefile
  cross/mp3gain/PLIST
  cross/mp3gain/digests
  cross/mp3gain/patches/001-Makefile-configure_install_path.patch
  cross/mpg123/Makefile
  cross/mpg123/PLIST
  cross/mpg123/digests
  python/dbus-python/Makefile
  python/dbus-python/PLIST
  python/dbus-python/digests
  python/lap/Makefile
  python/lap/digests
  python/pycairo/Makefile
  python/pycairo/PLIST
  python/pycairo/digests
  python/pygobject/Makefile
  python/pygobject/digests
  spk/beets/Makefile
  spk/beets/src/requirements-crossenv.txt
  spk/beets/src/requirements-pure.txt
  spk/beets/src/service-setup.sh
  spk/python312/crossenv/requirements-lap.txt
  spk/python312/crossenv/requirements-pygobject.txt
Labels: status/ready-to-merge
