Repository SynoCommunity/spksrc, pull requests merged in 2025-05, with the labels that each got.

#6509 synocli-disk: add mergerfs and update tools
  cross/dar/Makefile
  cross/dar/PLIST
  cross/dar/digests
  cross/disktype/Makefile
  cross/disktype/PLIST
  cross/disktype/digests
  cross/disktype/patches/001-adjust-makefile.patch
  cross/gpart/Makefile
  cross/gpart/PLIST
  cross/gpart/digests
  cross/gpart/patches/001-fix-version-number.patch
  cross/mergerfs/Makefile
  cross/mergerfs/PLIST
  cross/mergerfs/digests
  cross/mergerfs/patches/001-adjust-makefile.patch
  cross/mergerfs/patches/002-adjust-libfuse-makefile.patch
  cross/mergerfs/patches/003-use-predefined-version.patch
  cross/ncdu/Makefile
  cross/ncdu/digests
  diyspk/dar/Makefile
  diyspk/disktype/Makefile
  diyspk/gpart/Makefile
  diyspk/mergerfs/Makefile
  diyspk/ncdu/Makefile
  spk/synocli-disk/Makefile
Labels: synocli-disk

#6556 Python: Disable PEP 517 build isolation
  mk/spksrc.crossenv.mk
  mk/spksrc.python-wheel.mk
Labels: framework

#6573 python/pendulum: update to v3.1.0
  .github/workflows/build.yml
  python/pendulum/Makefile
  python/pendulum/digests
  python/pendulum/patches/001-rust-Use-i64-for-internal-unix-timestamps.patch
Labels: framework

#6429 ffsync: Update to v0.18.3 and migrate to Python 3.12
  cross/syncstorage-rs/Makefile
  cross/syncstorage-rs/digests
  cross/syncstorage-rs/patches/001-update-ring.patch
  spk/ffsync/Makefile
  spk/ffsync/src/requirements-crossenv-greenlet-v1.txt
  spk/ffsync/src/requirements-crossenv.txt
  spk/ffsync/src/requirements-pure.txt
  spk/ffsync/src/service-setup.sh
Labels: status/ready-to-merge, build/rust

#6574 add initial x25 models
  mk/spksrc.archs.mk
  toolchain/syno-x64-7.1/Makefile
  toolchain/syno-x64-7.2/Makefile
Labels: repo, arch

#6525 salt: Update to 3007.2 and migrate to Python 3.12
  cross/saltgui/Makefile
  cross/saltgui/digests
  cross/saltgui/src/salt-auth.txt
  spk/salt-master/Makefile
  spk/salt-master/src/app/master
  spk/salt-master/src/app/rsax931.py.patch
  spk/salt-master/src/app/salt-master.sc
  spk/salt-master/src/app/synology.py
  spk/salt-master/src/requirements-crossenv.txt
  spk/salt-master/src/requirements-pure.txt
  spk/salt-master/src/service-setup.sh
  spk/salt-minion/Makefile
  spk/salt-minion/src/app/minion
  spk/salt-minion/src/app/proxy
  spk/salt-minion/src/app/rsax931.py.patch
  spk/salt-minion/src/requirements-crossenv.txt
  spk/salt-minion/src/requirements-pure.txt
  spk/salt-minion/src/service-setup.sh
Labels: status/ready-to-merge

#6470 rdiff-backup: Migrate to Python 3.12
  spk/rdiff-backup/Makefile
  spk/rdiff-backup/src/requirements-crossenv.txt
  spk/rdiff-backup/src/requirements-pure.txt
  spk/rdiff-backup/src/service-setup.sh
Labels: status/ready-to-merge

#6580 add more x25 models
  mk/spksrc.archs.mk
  toolchain/syno-x64-7.1/Makefile
  toolchain/syno-x64-7.2/Makefile
Labels: framework, synology
